"""augmentation_spec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sMkJYxPIHGfyxX7jusVwvdloNJHZifJr
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/TechJammers-26/AI-Image-Detection.git
# %cd /content/AI-Image-Detection
!pip install -r requirements.txt --break-system-packages -q

import sys
sys.path.append('/content/AI-Image-Detection/src')

from aigcdet import augmentations

from google.colab import drive
drive.mount('/content/gdrive')

import os

GOOGLE_DRIVE_DATASET_PATH = '/content/gdrive/MyDrive/1_TikTok_TechJam_2026'

# Define the local directory where the dataset will be stored and unzipped
DATASET_DIR = '/content/dataset'
os.makedirs(DATASET_DIR, exist_ok=True)

# List of zip file names to process from GOOGLE_DRIVE_DATASET_PATH
ZIP_FILE_NAMES = [
    'sid_clean.zip',
    'cifake_clean.zip',
    'wildfake_clean.zip'
]

# Define TRAIN_ROOT and VAL_ROOT based on the local dataset directory
TRAIN_ROOT = os.path.join(DATASET_DIR, "train")
VAL_ROOT = os.path.join(DATASET_DIR, "val")
TEST_ROOT = os.path.join(DATASET_DIR, "test")

print(f"TRAIN_ROOT set to: {TRAIN_ROOT}")
print(f"VAL_ROOT set to: {VAL_ROOT}")
print(f"TEST_ROOT set to: {TEST_ROOT}")

import zipfile

print(f"Starting dataset extraction to: {DATASET_DIR}")

for zip_file_name in ZIP_FILE_NAMES:
    # Construct the full path to the zip file in Google Drive
    google_drive_zip_path = os.path.join(GOOGLE_DRIVE_DATASET_PATH, zip_file_name)

    # Define a temporary path for the zip file in the Colab environment
    temp_zip_path = os.path.join('/content', zip_file_name)

    print(f"Copying {zip_file_name} from Google Drive...")
    # Copy the zip file from Google Drive to the Colab environment
    !cp "{google_drive_zip_path}" "{temp_zip_path}"
    print(f"Copied {zip_file_name} to {temp_zip_path}")

    print(f"Unzipping {zip_file_name}...")
    # Unzip the file into the DATASET_DIR
    with zipfile.ZipFile(temp_zip_path, 'r') as zip_ref:
        zip_ref.extractall(DATASET_DIR)
    print(f"Unzipped {zip_file_name} to {DATASET_DIR}")

    # Remove the temporary zip file to save space
    os.remove(temp_zip_path)
    print(f"Removed temporary zip file: {temp_zip_path}")

print("All datasets extracted successfully!")

import os
import shutil

# Define the target consolidated directories
CONSOLIDATED_TRAIN_ROOT = os.path.join(DATASET_DIR, "train")
CONSOLIDATED_VAL_ROOT = os.path.join(DATASET_DIR, "val")
CONSOLIDATED_TEST_ROOT = os.path.join(DATASET_DIR, "test")

split_roots = {
    'train': CONSOLIDATED_TRAIN_ROOT,
    'val': CONSOLIDATED_VAL_ROOT,
    'test': CONSOLIDATED_TEST_ROOT,
}

# Create the consolidated root directories
for root in split_roots.values():
    os.makedirs(os.path.join(root, "real"), exist_ok=True)
    os.makedirs(os.path.join(root, "ai"), exist_ok=True)

# List of unzipped dataset base directories
UNZIPPED_DATASET_DIRS = [
    os.path.join(DATASET_DIR, 'sid_clean'),
    os.path.join(DATASET_DIR, 'cifake_dataset_clean'),
    os.path.join(DATASET_DIR, 'wildfake_clean')
]

print("Consolidating datasets...")

total_moved = 0
total_errors = 0

for dataset_base_dir in UNZIPPED_DATASET_DIRS:
    dataset_name = os.path.basename(dataset_base_dir)
    print(f"\nProcessing dataset: {dataset_base_dir}")

    if not os.path.exists(dataset_base_dir):
        print(f"  ERROR: dataset directory does not exist, skipping entirely: {dataset_base_dir}")
        total_errors += 1
        continue

    for split in ['train', 'val', 'test']:
        source_split_dir = os.path.join(dataset_base_dir, split)

        if not os.path.exists(source_split_dir):
            print(f"  WARNING: no '{split}' split found for {dataset_name}, skipping this split.")
            continue

        target_real_dir = os.path.join(split_roots[split], 'real')
        target_ai_dir = os.path.join(split_roots[split], 'ai')

        # ---- real ----
        source_real_dir = os.path.join(source_split_dir, 'real')
        if os.path.exists(source_real_dir):
            files = os.listdir(source_real_dir)
            if len(files) == 0:
                print(f"  WARNING: {source_real_dir} exists but is empty.")
            moved = 0
            for filename in files:
                src_path = os.path.join(source_real_dir, filename)
                if not os.path.isfile(src_path):
                    continue
                new_name = f"{dataset_name}_{filename}"
                dst_path = os.path.join(target_real_dir, new_name)
                if os.path.exists(dst_path):
                    print(f"    ERROR: collision, skipping: {new_name}")
                    total_errors += 1
                    continue
                try:
                    shutil.move(src_path, dst_path)
                    moved += 1
                except Exception as e:
                    print(f"    ERROR moving {src_path}: {e}")
                    total_errors += 1
            print(f"  Moved {moved} real images: {source_real_dir} -> {target_real_dir}")
            total_moved += moved
        else:
            print(f"  WARNING: no 'real' folder in {dataset_name}/{split}.")

        # ---- fake (-> ai) ----
        source_fake_dir = os.path.join(source_split_dir, 'fake')
        if os.path.exists(source_fake_dir):
            files = os.listdir(source_fake_dir)
            if len(files) == 0:
                print(f"  WARNING: {source_fake_dir} exists but is empty.")
            moved = 0
            for filename in files:
                src_path = os.path.join(source_fake_dir, filename)
                if not os.path.isfile(src_path):
                    continue
                new_name = f"{dataset_name}_{filename}"
                dst_path = os.path.join(target_ai_dir, new_name)
                if os.path.exists(dst_path):
                    print(f"    ERROR: collision, skipping: {new_name}")
                    total_errors += 1
                    continue
                try:
                    shutil.move(src_path, dst_path)
                    moved += 1
                except Exception as e:
                    print(f"    ERROR moving {src_path}: {e}")
                    total_errors += 1
            print(f"  Moved {moved} fake images: {source_fake_dir} -> {target_ai_dir} (as ai)")
            total_moved += moved
        else:
            print(f"  WARNING: no 'fake' folder in {dataset_name}/{split}.")

print(f"\nTotal images moved: {total_moved}")
print(f"Total errors: {total_errors}")

if total_errors > 0:
    print("\n!! Errors occurred during consolidation. Review the log above before deleting source folders. !!")

print("Dataset consolidation complete!")

# Re-run the ROOT definitions after consolidation
TRAIN_ROOT = CONSOLIDATED_TRAIN_ROOT
VAL_ROOT = CONSOLIDATED_VAL_ROOT
TEST_ROOT = CONSOLIDATED_TEST_ROOT
print(f"TRAIN_ROOT re-set to: {TRAIN_ROOT}")
print(f"VAL_ROOT re-set to: {VAL_ROOT}")
print(f"TEST_ROOT re-set to: {TEST_ROOT}")

for split in ['train', 'val', 'test']:
    for cls in ['real', 'ai']:
        path = os.path.join(DATASET_DIR, split, cls)
        if os.path.exists(path):
            count = len(os.listdir(path))
            print(f"{split}/{cls}: {count} files")
        else:
            print(f"{split}/{cls}: MISSING")

#this is to save space, only run when extracted successfully!!!
# print("Cleaning up original dataset folders...")
# for dataset_base_dir in UNZIPPED_DATASET_DIRS:
#      if os.path.exists(dataset_base_dir):
#          shutil.rmtree(dataset_base_dir)
#          print(f"Removed {dataset_base_dir}")

import sys
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from PIL import Image

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import models, transforms

from sklearn.metrics import accuracy_score, roc_auc_score


# CELL 1 — REPRODUCIBILITY
SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)


def worker_init_fn(worker_id):
    """
    Reseed each DataLoader worker independently. Without this, forked
    workers can share correlated RNG state (see review note #5) which
    quietly reduces augmentation diversity. Cheap to add, so it's on
    by default here even though it's optional for a hackathon timeline.
    """
    worker_seed = (SEED + worker_id) % (2**32)
    np.random.seed(worker_seed)
    random.seed(worker_seed)

"""Config"""

BACKBONE = "efficientnet_b0"
POLICY = "spec"  #this run is the spec checkpoint

IMAGE_SIZE = 224
BATCH_SIZE = 32

EPOCHS = 6

LEARNING_RATE = 1e-4
WEIGHT_DECAY = 1e-4

NUM_WORKERS = 2

TRAIN_ROOT = os.path.join(DATASET_DIR, "train")
VAL_ROOT = os.path.join(DATASET_DIR, "val")
TEST_ROOT = os.path.join(DATASET_DIR, "test")

print(f"TRAIN_ROOT: {TRAIN_ROOT}")
print(f"VAL_ROOT:   {VAL_ROOT}")
print(f"TEST_ROOT:  {TEST_ROOT}")

for split_name, root in [("train", TRAIN_ROOT), ("val", VAL_ROOT), ("test", TEST_ROOT)]:
    for cls in ["real", "ai"]:
        path = os.path.join(root, cls)
        if os.path.exists(path):
            print(f"{split_name}/{cls}: {len(os.listdir(path))} files")
        else:
            print(f"{split_name}/{cls}: MISSING — check consolidation before continuing")

# Checkpoint path — separate dir per policy so runs never collide
CHECKPOINT_DIR = "/content/gdrive/MyDrive/TikTok TechJam/checkpoints"
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

CHECKPOINT_PATH = os.path.join(CHECKPOINT_DIR, f"{BACKBONE}_{POLICY}_best.pth")

print("Policy:", POLICY)
print("Checkpoint will be saved to:", CHECKPOINT_PATH)

"""Import Augmentations"""

REPO_PATH = "/content/AI-Image-Detection/src/aigcdet"

if REPO_PATH not in sys.path:
    sys.path.append(REPO_PATH)

from augmentations import (
    build_train_augment,
    apply_eval_transform,
    eval_names,
    get_eval_transform,
    canonicalize,
)

train_augmenter = build_train_augment(
    policy=POLICY,
    n_ops=(0, 2),
    p=0.9,
    seed=SEED,
)

augmentation_config = train_augmenter.config()
print(augmentation_config)

"""Dataset Class"""

class AIImageDataset(Dataset):
    def __init__(self, root_dir, geometric_transform=None, augmenter=None):
        self.root_dir = root_dir
        self.geometric_transform = geometric_transform
        self.augmenter = augmenter

        self.samples = []

        class_mapping = {"real": 0, "ai": 1}

        valid_extensions = (".jpg", ".jpeg", ".png", ".webp", ".bmp")

        for class_name, label in class_mapping.items():
            class_dir = os.path.join(root_dir, class_name)

            if not os.path.exists(class_dir):
                raise FileNotFoundError(f"Cannot find folder: {class_dir}")

            for filename in os.listdir(class_dir):
                if filename.lower().endswith(valid_extensions):
                    filepath = os.path.join(class_dir, filename)
                    self.samples.append((filepath, label))

        print(f"Loaded {len(self.samples)} images from {root_dir}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        filepath, label = self.samples[idx]
        image_key = os.path.relpath(filepath, self.root_dir)

        image = Image.open(filepath).convert("RGB")
        image = canonicalize(image)

        if self.augmenter is not None:
            image = self.augmenter(image, image_key=image_key)

        if self.geometric_transform is not None:
            image = self.geometric_transform(image)

        return image, label

"""Transformation"""

train_geometric_transform = transforms.Compose([
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225],
    ),
])

val_geometric_transform = transforms.Compose([
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225],
    ),
])

"""Loading Data"""

try:
    train_dataset = AIImageDataset(
        root_dir=TRAIN_ROOT,
        geometric_transform=train_geometric_transform,
        augmenter=train_augmenter,
    )
    val_dataset = AIImageDataset(
        root_dir=VAL_ROOT,
        geometric_transform=val_geometric_transform,
        augmenter=None,  # no policy augmentation on val, canonicalize still applies
    )
except FileNotFoundError as e:
    print(f"Error: {e}. Please ensure the dataset directories are correctly set up.")
    train_dataset = None
    val_dataset = None

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=True,
    worker_init_fn=worker_init_fn,
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True,
)

print("Training batches:", len(train_loader))
print("Validation batches:", len(val_loader))

images, labels = next(iter(train_loader))
print("Image batch shape:", images.shape)
print("Label batch shape:", labels.shape)
print("Example labels:", labels[:10])

"""Model"""

weights = models.EfficientNet_B0_Weights.DEFAULT
model = models.efficientnet_b0(weights=weights)

in_features = model.classifier[1].in_features
model.classifier[1] = nn.Linear(in_features, 1)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)
print(model.classifier)

criterion = nn.BCEWithLogitsLoss()

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY,
)

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS)

"""Resume from saved epoch"""

start_epoch = 0
best_val_auc = -1.0
best_epoch = -1

if os.path.exists(CHECKPOINT_PATH):
    print(f"Found existing checkpoint at {CHECKPOINT_PATH}, resuming...")

    ckpt = torch.load(CHECKPOINT_PATH, map_location=device, weights_only=False)

    model.load_state_dict(ckpt["model_state_dict"])
    optimizer.load_state_dict(ckpt["optimizer_state_dict"])

    # Fast-forward the scheduler so LR picks up where it left off
    for _ in range(ckpt["epoch"]):
        scheduler.step()

    start_epoch = ckpt["epoch"]
    best_val_auc = ckpt["val_auc"]
    best_epoch = ckpt["epoch"]

    print(f"Resumed from epoch {start_epoch}, best val AUC so far: {best_val_auc:.4f}")
else:
    print("No existing checkpoint found — starting fresh from epoch 0.")

"""Train/ Eval Functions"""

def train_one_epoch(model, loader, criterion, optimizer, device):
    model.train()

    total_loss = 0
    probabilities = []
    ground_truth = []

    for images, labels in loader:
        images = images.to(device, non_blocking=True)
        labels = labels.float().to(device, non_blocking=True)  # BCEWithLogitsLoss needs float labels

        optimizer.zero_grad()

        logits = model(images).squeeze(1)
        loss = criterion(logits, labels)

        loss.backward()
        optimizer.step()

        total_loss += loss.item() * images.size(0)

        probs = torch.sigmoid(logits)
        probabilities.extend(probs.detach().cpu().numpy())
        ground_truth.extend(labels.detach().cpu().numpy())

    epoch_loss = total_loss / len(loader.dataset)

    probabilities = np.array(probabilities)
    ground_truth = np.array(ground_truth)
    predictions = (probabilities >= 0.5).astype(int)

    accuracy = accuracy_score(ground_truth, predictions)
    auc = roc_auc_score(ground_truth, probabilities)

    return epoch_loss, accuracy, auc


def evaluate_model(model, loader, criterion, device):
    model.eval()

    total_loss = 0
    probabilities = []
    ground_truth = []

    with torch.no_grad():
        for images, labels in loader:
            images = images.to(device, non_blocking=True)
            labels = labels.float().to(device, non_blocking=True)

            logits = model(images).squeeze(1)
            loss = criterion(logits, labels)

            total_loss += loss.item() * images.size(0)

            probs = torch.sigmoid(logits)
            probabilities.extend(probs.cpu().numpy())
            ground_truth.extend(labels.cpu().numpy())

    loss = total_loss / len(loader.dataset)

    probabilities = np.array(probabilities)
    ground_truth = np.array(ground_truth)
    predictions = (probabilities >= 0.5).astype(int)

    accuracy = accuracy_score(ground_truth, predictions)
    auc = roc_auc_score(ground_truth, probabilities)

    return loss, accuracy, auc

"""Training Loop"""

history = {
    "epoch": [], "train_loss": [], "train_accuracy": [], "train_auc": [],
    "val_loss": [], "val_accuracy": [], "val_auc": [],
}

for epoch in range(EPOCHS):
    print()
    print(f"Epoch {epoch + 1}/{EPOCHS}")
    print("=" * 50)

    train_loss, train_accuracy, train_auc = train_one_epoch(
        model, train_loader, criterion, optimizer, device
    )

    val_loss, val_accuracy, val_auc = evaluate_model(
        model, val_loader, criterion, device
    )

    history["epoch"].append(epoch + 1)
    history["train_loss"].append(train_loss)
    history["train_accuracy"].append(train_accuracy)
    history["train_auc"].append(train_auc)
    history["val_loss"].append(val_loss)
    history["val_accuracy"].append(val_accuracy)
    history["val_auc"].append(val_auc)

    print(f"Train Loss: {train_loss:.4f}")
    print(f"Train Accuracy: {train_accuracy:.4f}")
    print(f"Train AUC: {train_auc:.4f}")
    print()
    print(f"Clean Val Loss: {val_loss:.4f}")
    print(f"Clean Val Accuracy: {val_accuracy:.4f}")
    print(f"Clean Val AUC: {val_auc:.4f}")

    # SAVE BEST CHECKPOINT (by AUC)
    if val_auc > best_val_auc:
        best_val_auc = val_auc
        best_epoch = epoch + 1

        checkpoint = {
            "epoch": best_epoch,
            "model_state_dict": model.state_dict(),
            "optimizer_state_dict": optimizer.state_dict(),
            "val_accuracy": val_accuracy,
            "val_auc": val_auc,
            "val_loss": val_loss,
            "policy": POLICY,
            "augmentation_config": train_augmenter.config(),
            "backbone": BACKBONE,
            "image_size": IMAGE_SIZE,
            "batch_size": BATCH_SIZE,
            "learning_rate": LEARNING_RATE,
            "weight_decay": WEIGHT_DECAY,
            "seed": SEED,
        }

        torch.save(checkpoint, CHECKPOINT_PATH)

        print()
        print("New best checkpoint saved")
        print("Best epoch:", best_epoch)
        print("Best AUC:", f"{best_val_auc:.4f}")

    scheduler.step()

print()
print("=" * 50)
print("TRAINING COMPLETE")
print("Policy:", POLICY)
print("Best epoch:", best_epoch)
print("Best clean AUC:", best_val_auc)
print("Checkpoint:", CHECKPOINT_PATH)

"""Plots"""

history_df = pd.DataFrame(history)
print(history_df)

plt.figure(figsize=(8, 5))
plt.plot(history_df["epoch"], history_df["train_loss"], label="Train Loss")
plt.plot(history_df["epoch"], history_df["val_loss"], label="Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title(f"Loss — EfficientNet-B0 ({POLICY})")
plt.legend()
plt.show()

plt.figure(figsize=(8, 5))
plt.plot(history_df["epoch"], history_df["train_accuracy"], label="Train Accuracy")
plt.plot(history_df["epoch"], history_df["val_accuracy"], label="Clean Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title(f"Accuracy — EfficientNet-B0 ({POLICY})")
plt.legend()
plt.show()

plt.figure(figsize=(8, 5))
plt.plot(history_df["epoch"], history_df["train_auc"], label="Train AUC")
plt.plot(history_df["epoch"], history_df["val_auc"], label="Clean Validation AUC")
plt.xlabel("Epoch")
plt.ylabel("ROC-AUC")
plt.title(f"AUC — EfficientNet-B0 ({POLICY})")
plt.legend()
plt.show()

"""Verify best pth"""

checkpoint = torch.load(CHECKPOINT_PATH, map_location=device, weights_only=False)

model.load_state_dict(checkpoint["model_state_dict"])
model = model.to(device)

print("Loaded checkpoint:")
print("Policy:", checkpoint["policy"])
print("Best epoch:", checkpoint["epoch"])
print("Clean val accuracy:", checkpoint["val_accuracy"])
print("Clean val AUC:", checkpoint["val_auc"])

best_val_loss, best_val_acc, best_val_auc = evaluate_model(
    model, val_loader, criterion, device
)

print(f"Reloaded checkpoint accuracy: {best_val_acc:.4f}")
print(f"Reloaded checkpoint AUC: {best_val_auc:.4f}")
