# -*- coding: utf-8 -*-
"""data_pipeline_and_curation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TMuz1vXvWzA0kHdoC59lZETkmXsxTKE8
"""

!pip install imagehash

# Requirements.txt
# TechJammers dataset tooling + training data loader
# Tested with Python 3.13 (torch has no 3.14 wheels yet). Set up:
#   python3.13 -m venv .venv && .venv/bin/pip install -r requirements.txt
torch==2.13.0
torchvision==0.28.0
Pillow==12.3.0
imagehash==4.3.2      # dataset_sanity_check.py near-dupe detection
numpy==2.5.2          # imagehash dependency
kagglehub==1.0.2      # download_cifake.py — dataset download

"""# Import SID"""

"""
download_SID.py

Downloads SID_Set from Hugging Face and inspects its structure so you know
what restructure_dataset.py and data_loader.py need to handle.

SID_Set is NOT shipped as loose image files in folders — it's stored as
parquet with an `image` column, a `mask` column, and a `label` column
(0=real, 1=full_synthetic, 2=tampered). This script downloads it, saves a
sample of images to disk so you can SEE the actual structure, and prints
a structure report.

Usage (from the project root):
    pip install datasets huggingface_hub pillow --break-system-packages
    python3 download_scripts/download_sid.py --sample-size 200 --out ./data/sid_set_sample
"""

import argparse
import os
from collections import Counter
from pathlib import Path

from datasets import load_dataset


LABEL_NAMES = {0: "real", 1: "full_synthetic", 2: "tampered"}


def download_and_sample(out_dir: Path, sample_size: int, split: str):
    """
    Load SID_Set (streaming, to avoid pulling the full 140GB) and save a
    sample of images + masks to disk so you can inspect real files.
    """
    print(f"Loading SID_Set split='{split}' in streaming mode (dataset is ~140GB total)...")
    ds = load_dataset("saberzl/SID_Set", split=split, streaming=True)

    out_dir.mkdir(parents=True, exist_ok=True)
    label_counts = Counter()
    mask_counts = Counter()

    print(f"Saving a sample of {sample_size} rows to {out_dir} ...")
    for i, row in enumerate(ds):
        if i >= sample_size:
            break

        label = row["label"]
        label_name = LABEL_NAMES.get(label, f"unknown_{label}")
        label_counts[label_name] += 1

        class_dir = out_dir / label_name
        class_dir.mkdir(parents=True, exist_ok=True)

        img = row["image"]
        img_id = row.get("img_id", f"row_{i}")
        img_path = class_dir / f"{img_id}.jpg"
        img.save(img_path)

        mask = row.get("mask")
        if mask is not None:
            mask_dir = out_dir / f"{label_name}_masks"
            mask_dir.mkdir(parents=True, exist_ok=True)
            mask.save(mask_dir / f"{img_id}_mask.jpg")
            mask_counts[label_name] += 1

    print(f"\nSaved {sum(label_counts.values())} sample images.")
    print("Label distribution in this sample:", dict(label_counts))
    print("Rows with a mask, by label:", dict(mask_counts))
    return label_counts, mask_counts


def inspect_structure(root: Path):
    """Walk the saved sample and print a structure report."""
    print(f"\n{'='*60}")
    print(f"STRUCTURE REPORT: {root}")
    print(f"{'='*60}\n")

    if not root.exists():
        print(f"Nothing found at {root} — did the download step run?")
        return

    print("Top-level folders found:")
    top_level = sorted([p.name for p in root.iterdir() if p.is_dir()])
    for name in top_level:
        n_files = len(list((root / name).glob("*")))
        print(f"  {name}/  ({n_files} files)")

    print("\nFile extensions found:")
    ext_counter = Counter()
    for f in root.rglob("*"):
        if f.is_file():
            ext_counter[f.suffix.lower()] += 1
    for ext, count in sorted(ext_counter.items(), key=lambda x: -x[1]):
        print(f"  {ext or '(no extension)'}: {count}")

    print("\nSample file paths (first 10):")
    for f in list(root.rglob("*.jpg"))[:10]:
        print(f"  {f.relative_to(root)}")

    print(f"""
{'='*60}
WHAT THIS MEANS FOR restructure_dataset.py:
{'='*60}
- SID_Set has 3 source classes: real (0), full_synthetic (1), tampered (2).
  Your restructure script needs to map: real -> real, {{full_synthetic, tampered}} -> fake.
- Tampered rows also have a mask image. Decide: do you need masks for this
  project, or only the images + real/fake label? If you don't need
  segmentation masks, restructure_dataset.py should just skip the mask
  column entirely — don't copy masks into the train/val/test folders,
  or your sanity check script will scan them as if they were training images.
- Images come from a parquet/streaming source, not loose files — so
  restructure_dataset.py cannot just os.walk() the raw download like it can
  for CIFAKE. It needs to iterate the HF dataset object (load_dataset(...,
  streaming=True) or non-streaming) and write out .jpg files itself, same
  as the download_and_sample() function above does.
- Full dataset is 210k train + 30k val (test is withheld separately, see
  https://github.com/hzlsaber/SIDA). At 140GB total, decide whether you
  want to (a) download and restructure the full thing, or (b) subsample
  per class to keep the working dataset size manageable.
""")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--split", default="train", choices=["train", "validation"],
                     help="Which SID_Set split to sample from")
    ap.add_argument("--sample-size", type=int, default=200,
                     help="Number of rows to download and save for inspection")
    ap.add_argument("--out", default="./data/sid_set_sample",
                     help="Where to save the sample images")
    args = ap.parse_args()

    out_dir = Path(args.out)
    download_and_sample(out_dir, args.sample_size, args.split)
    inspect_structure(out_dir)


if __name__ == "__main__":
    main()

"""# Import CIFAKE"""

"""
download_cifake.py
==================

Download the CIFAKE dataset via kagglehub (replaces the old Kaggle CLI flow).

CIFAKE is a public dataset, so this works without Kaggle credentials. kagglehub
caches the files under ~/.cache/kagglehub/ (NOT in this project) and pins a
dataset version, so re-running is cheap: if the cache is already complete it
just prints the path without re-downloading.

Requires:  pip install kagglehub

Usage (from the project root):
    python3 download_scripts/download_cifake.py
"""

import kagglehub

DATASET = "birdy654/cifake-real-and-ai-generated-synthetic-images"


def main() -> str:
    path = kagglehub.dataset_download(DATASET)
    print("Path to dataset files:", path)
    return path


if __name__ == "__main__":
    main()

"""# Data sanity check"""

import torch


#!/usr/bin/env python3
"""Sanity-check an ImageFolder-style dataset: <root>/<split>/<class>/*.img

Reports:
  * image counts per split/class and class balance
  * unexpected file types / extension-vs-format mismatches
  * corrupted / unreadable images
  * exact-duplicate groups (flags cross-split leakage)
  * near-duplicate groups (with --near-dupes)
  * missing data (empty class dirs, splits missing a class)

Exit code: 0 = clean, 1 = warnings, 2 = failures.

Usage:
  python dataset_sanity_check.py ./data/dataset [--near-dupes]
                                 [--near-dupe-threshold 5] [--workers N]
"""
from __future__ import annotations

import argparse
import hashlib
import sys
import warnings
from collections import defaultdict
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path

from PIL import Image, ImageFile
import imagehash

# surface truncated-file warnings as errors so they count as corruption
warnings.simplefilter("error", Image.DecompressionBombWarning)
ImageFile.LOAD_TRUNCATED_IMAGES = False

IMG_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".gif", ".webp", ".tif", ".tiff"}
EXPECTED_SPLITS = ("train", "val", "test")
BALANCE_TOL = 0.10  # fraction deviation from an even class split before WARN


# --------------------------------------------------------------------------- #
# per-file worker
# --------------------------------------------------------------------------- #
def inspect(path_str: str, want_phash: bool):
    """Return dict describing one file. Runs in a worker process."""
    p = Path(path_str)
    out = {
        "path": path_str,
        "ext_ok": p.suffix.lower() in IMG_EXTS,
        "corrupt": False,
        "error": "",
        "fmt": "",
        "fmt_mismatch": False,
        "sha256": "",
        "phash": "",
    }
    try:
        data = p.read_bytes()
        out["sha256"] = hashlib.sha256(data).hexdigest()
    except OSError as e:
        out["corrupt"] = True
        out["error"] = f"read: {e}"
        return out

    try:
        with Image.open(p) as im:
            im.verify()  # cheap structural check
        with Image.open(p) as im:
            im.load()  # force full decode
            rgb = im.convert("RGB")
            out["fmt"] = (im.format or "").upper()
            if want_phash:
                out["phash"] = str(imagehash.phash(rgb))
    except Exception as e:  # noqa: BLE001 - PIL raises many types
        out["corrupt"] = True
        out["error"] = f"decode: {type(e).__name__}: {e}"
        return out

    ext = p.suffix.lower().lstrip(".")
    ext_norm = {"jpg": "JPEG", "jpeg": "JPEG", "tif": "TIFF", "tiff": "TIFF"}.get(ext, ext.upper())
    if out["fmt"] and ext_norm != out["fmt"]:
        out["fmt_mismatch"] = True
    return out


# --------------------------------------------------------------------------- #
# near-dupe grouping via BK-tree over perceptual hashes
# --------------------------------------------------------------------------- #
class BKTree:
    def __init__(self):
        self.root = None  # (hash_int, children: {dist: node})

    @staticmethod
    def _d(a, b):
        return bin(a ^ b).count("1")

    def add(self, h):
        if self.root is None:
            self.root = [h, {}]
            return
        node = self.root
        while True:
            dist = self._d(h, node[0])
            child = node[1].get(dist)
            if child is None:
                node[1][dist] = [h, {}]
                return
            node = child

    def query(self, h, tol):
        if self.root is None:
            return []
        found, stack = [], [self.root]
        while stack:
            node = stack.pop()
            dist = self._d(h, node[0])
            if dist <= tol:
                found.append(node[0])
            for edge, child in node[1].items():
                if dist - tol <= edge <= dist + tol:
                    stack.append(child)
        return found


class Union:
    def __init__(self):
        self.parent = {}

    def find(self, x):
        self.parent.setdefault(x, x)
        while self.parent[x] != x:
            self.parent[x] = self.parent[self.parent[x]]
            x = self.parent[x]
        return x

    def union(self, a, b):
        ra, rb = self.find(a), self.find(b)
        if ra != rb:
            self.parent[ra] = rb


# --------------------------------------------------------------------------- #
def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("root", type=Path, help="dataset root containing <split>/<class>/ dirs")
    ap.add_argument("--near-dupes", action="store_true", help="also detect near-duplicate images")
    ap.add_argument("--near-dupe-threshold", type=int, default=5,
                    help="max Hamming distance between pHashes to call a near-dupe (default 5)")
    ap.add_argument("--workers", type=int, default=0, help="worker processes (0 = auto)")
    ap.add_argument("--max-list", type=int, default=15, help="max example rows to print per issue")
    args = ap.parse_args()

    root: Path = args.root
    if not root.is_dir():
        print(f"FATAL: not a directory: {root}", file=sys.stderr)
        sys.exit(2)

    # ---- discover layout ----------------------------------------------------
    splits = sorted(d.name for d in root.iterdir() if d.is_dir())
    if not splits:
        print(f"FATAL: no split subdirectories under {root}", file=sys.stderr)
        sys.exit(2)

    files: list[tuple[str, str, str]] = []  # (split, class, path)
    non_image_files: list[str] = []
    classes_by_split: dict[str, set[str]] = defaultdict(set)
    empty_class_dirs: list[str] = []

    for split in splits:
        for cdir in sorted(p for p in (root / split).iterdir() if p.is_dir()):
            classes_by_split[split].add(cdir.name)
            n_here = 0
            for f in cdir.iterdir():
                if f.name == ".DS_Store" or f.name.startswith("."):
                    continue
                if not f.is_file():
                    continue
                if f.suffix.lower() in IMG_EXTS:
                    files.append((split, cdir.name, str(f)))
                    n_here += 1
                else:
                    non_image_files.append(str(f))
            if n_here == 0:
                empty_class_dirs.append(f"{split}/{cdir.name}")

    if not files:
        print("FATAL: found no image files at all", file=sys.stderr)
        sys.exit(2)

    print(f"Scanning {len(files):,} files under {root} ...")
    workers = args.workers or None
    results = []
    with ProcessPoolExecutor(max_workers=workers) as ex:
        for r in ex.map(inspect, [f[2] for f in files],
                        [args.near_dupes] * len(files), chunksize=256):
            results.append(r)

    by_path = {r["path"]: r for r in results}

    # ---- counts -----------------------------------------------------------
    counts: dict[tuple[str, str], int] = defaultdict(int)
    all_classes = set()
    for split, cls, _ in files:
        counts[(split, cls)] += 1
        all_classes.add(cls)
    all_classes = sorted(all_classes)

    warn, fail = [], []

    print("\n" + "=" * 60)
    print("IMAGE COUNTS")
    print("=" * 60)
    print(f"{'split':<10}{'class':<10}{'count':>12}")
    print("-" * 32)
    grand = 0
    for split in splits:
        sub = 0
        for cls in all_classes:
            c = counts.get((split, cls), 0)
            sub += c
            grand += c
            print(f"{split:<10}{cls:<10}{c:>12,}")
        print(f"{'':<10}{'TOTAL':<10}{sub:>12,}")
    print("-" * 32)
    print(f"{'':<10}{'GRAND':<10}{grand:>12,}")

    # ---- class balance --------------------------------------------------
    print("\n" + "=" * 60)
    print("CLASS BALANCE")
    print("=" * 60)
    for split in splits:
        row = {cls: counts.get((split, cls), 0) for cls in all_classes}
        tot = sum(row.values())
        if tot == 0:
            fail.append(f"split '{split}' has zero images")
            continue
        frac = {cls: n / tot for cls, n in row.items()}
        even = 1 / len(all_classes)
        desc = "  ".join(f"{cls}={n:,} ({frac[cls]*100:.1f}%)" for cls, n in row.items())
        print(f"{split:<8} {desc}")
        worst = max(abs(f - even) for f in frac.values())
        if worst > BALANCE_TOL:
            warn.append(f"'{split}' class imbalance: {desc} (>{BALANCE_TOL*100:.0f}% from even)")

    # ---- structural / missing ----------------------------------------
    print("\n" + "=" * 60)
    print("STRUCTURE")
    print("=" * 60)
    ref_classes = set(all_classes)
    for split in splits:
        missing = ref_classes - classes_by_split[split]
        if missing:
            fail.append(f"split '{split}' missing class dir(s): {sorted(missing)}")
    for d in empty_class_dirs:
        fail.append(f"empty class directory: {d}")
    for split in EXPECTED_SPLITS:
        if split not in splits:
            warn.append(f"expected split '{split}' not present")
    print(f"splits found : {splits}")
    print(f"classes found: {all_classes}")
    print(f"empty class dirs: {empty_class_dirs or 'none'}")

    # ---- file types --------------------------------------------------
    print("\n" + "=" * 60)
    print("FILE TYPES")
    print("=" * 60)
    fmt_counts = defaultdict(int)
    mismatches = []
    for r in results:
        if r["corrupt"]:
            continue
        fmt_counts[r["fmt"] or "?"] += 1
        if r["fmt_mismatch"]:
            mismatches.append(r["path"])
    for fmt, n in sorted(fmt_counts.items(), key=lambda kv: -kv[1]):
        print(f"  {fmt:<8} {n:>10,}")
    if non_image_files:
        warn.append(f"{len(non_image_files)} non-image file(s) present, e.g. "
                    + ", ".join(Path(p).name for p in non_image_files[:5]))
        print(f"  non-image files: {len(non_image_files)}")
    if mismatches:
        warn.append(f"{len(mismatches)} file(s) whose extension disagrees with actual format")
        print(f"  extension/format mismatches: {len(mismatches)}")
        for p in mismatches[: args.max_list]:
            rel = Path(p).relative_to(root)
            print(f"    {rel}  -> actual {by_path[p]['fmt']}")

    # ---- corruption ------------------------------------------------
    print("\n" + "=" * 60)
    print("CORRUPTED / UNREADABLE")
    print("=" * 60)
    corrupt = [r for r in results if r["corrupt"]]
    if not corrupt:
        print("  none ✓")
    else:
        fail.append(f"{len(corrupt)} corrupted/unreadable image(s)")
        for r in corrupt[: args.max_list]:
            rel = Path(r["path"]).relative_to(root)
            print(f"  {rel}  --  {r['error']}")
        if len(corrupt) > args.max_list:
            print(f"  ... and {len(corrupt) - args.max_list} more")

    # ---- exact duplicates ----------------------------------------
    print("\n" + "=" * 60)
    print("EXACT DUPLICATES (identical file bytes)")
    print("=" * 60)
    by_hash = defaultdict(list)
    for r in results:
        if r["sha256"] and not r["corrupt"]:
            by_hash[r["sha256"]].append(r["path"])
    dup_groups = [g for g in by_hash.values() if len(g) > 1]
    dup_files = sum(len(g) - 1 for g in dup_groups)
    cross_split = 0
    if not dup_groups:
        print("  none ✓")
    else:
        for g in dup_groups:
            sps = {Path(p).relative_to(root).parts[0] for p in g}
            if len(sps) > 1:
                cross_split += 1
        print(f"  {len(dup_groups):,} duplicate group(s), {dup_files:,} redundant file(s)")
        if cross_split:
            print(f"  {cross_split:,} group(s) span MULTIPLE SPLITS (train/val/test leakage)")
        for g in sorted(dup_groups, key=len, reverse=True)[: args.max_list]:
            rels = [str(Path(p).relative_to(root)) for p in sorted(g)]
            print(f"  x{len(g)}: " + "  |  ".join(rels[:4]) + (" ..." if len(rels) > 4 else ""))
        warn.append(f"{len(dup_groups)} exact-duplicate group(s) ({dup_files} redundant files)")
        if cross_split:
            fail.append(f"{cross_split} duplicate group(s) leak across splits")

    # ---- near duplicates ---------------------------------------
    if args.near_dupes:
        print("\n" + "=" * 60)
        print(f"NEAR DUPLICATES (pHash Hamming <= {args.near_dupe_threshold})")
        print("=" * 60)
        tol = args.near_dupe_threshold
        phash_to_paths = defaultdict(list)
        for r in results:
            if r["phash"] and not r["corrupt"]:
                phash_to_paths[int(str(r["phash"]), 16)].append(r["path"])

        tree = BKTree()
        for h in phash_to_paths:
            tree.add(h)
        uf = Union()
        for h in phash_to_paths:
            for h2 in tree.query(h, tol):
                if h2 != h:
                    uf.union(h, h2)

        clusters = defaultdict(list)
        for h, paths in phash_to_paths.items():
            clusters[uf.find(h)].extend(paths)
        near_groups = [g for g in clusters.values() if len(g) > 1]
        # subtract exact-dup redundancy already reported
        near_only = [g for g in near_groups
                     if len({by_path[p]["sha256"] for p in g}) > 1]
        near_files = sum(len(g) - 1 for g in near_groups)
        n_cross = 0
        for g in near_groups:
            if len({Path(p).relative_to(root).parts[0] for p in g}) > 1:
                n_cross += 1
        if not near_groups:
            print("  none ✓")
        else:
            print(f"  {len(near_groups):,} near-dupe cluster(s), {near_files:,} extra image(s)")
            print(f"  {len(near_only):,} cluster(s) are NOT already exact duplicates")
            if n_cross:
                print(f"  {n_cross:,} cluster(s) span multiple splits (leakage risk)")
            for g in sorted(near_groups, key=len, reverse=True)[: args.max_list]:
                rels = [str(Path(p).relative_to(root)) for p in sorted(g)]
                print(f"  x{len(g)}: " + "  |  ".join(rels[:4]) + (" ..." if len(rels) > 4 else ""))
            warn.append(f"{len(near_groups)} near-duplicate cluster(s) ({near_files} extra images)")
            if n_cross:
                fail.append(f"{n_cross} near-duplicate cluster(s) span splits")

    # ---- verdict --------------------------------------------------
    print("\n" + "=" * 60)
    print("VERDICT")
    print("=" * 60)
    if fail:
        print("FAIL:")
        for m in fail:
            print(f"  ✗ {m}")
    if warn:
        print("WARN:")
        for m in warn:
            print(f"  ! {m}")
    if not fail and not warn:
        print("PASS — no issues detected ✓")

    sys.exit(2 if fail else (1 if warn else 0))


if __name__ == "__main__":
    main()

"""# Data Restructuring"""

#!/usr/bin/env python3
"""Restructure a raw {train,test}/{CLASS}/ image download into ImageFolder format.

Default layout produced:

    <dst>/train/<class>/   (from <src>/train, minus the val slice)
    <dst>/val/<class>/     (val-fraction of <src>/train, stratified by class)
    <dst>/test/<class>/    (copied as-is from <src>/test -- held-out test set)

Class sub-folder names are lower-cased (REAL -> real, FAKE -> fake).
Files are COPIED, never moved -- the raw <src> download is left untouched.

Examples
--------
Default (CIFAKE, our original CLI download in ./archive):

    python3 restructure_dataset.py

Point at a fresh kagglehub download and write to a scratch folder:

    python3 restructure_dataset.py \\
        --src ~/.cache/kagglehub/datasets/birdy654/cifake-real-and-ai-generated-synthetic-images/versions/3 \\
        --dst ./data/dataset_test
"""
import argparse
import random
import shutil
from pathlib import Path

DEFAULT_SEED = 42
DEFAULT_VAL_FRACTION = 0.15
DEFAULT_SRC = Path("archive")
DEFAULT_DST = Path("data/dataset")
IMG_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".gif", ".webp"}


def list_images(folder: Path):
    return sorted(p for p in folder.iterdir() if p.is_file() and p.suffix.lower() in IMG_EXTS)


def copy_all(files, dst_dir: Path):
    dst_dir.mkdir(parents=True, exist_ok=True)
    for f in files:
        shutil.copy2(f, dst_dir / f.name)


def discover_classes(split_dir: Path):
    """Return {raw_name: lowercased_name} for every class sub-folder in a split."""
    return {d.name: d.name.lower() for d in sorted(split_dir.iterdir()) if d.is_dir()}


def restructure(src: Path, dst: Path, seed: int, val_fraction: float):
    random.seed(seed)
    assert src.exists(), f"missing source folder: {src}"
    assert (src / "train").is_dir(), f"missing {src/'train'}"
    assert (src / "test").is_dir(), f"missing {src/'test'}"

    train_classes = discover_classes(src / "train")
    test_classes = discover_classes(src / "test")
    assert train_classes, f"no class sub-folders under {src/'train'}"
    assert set(train_classes) == set(test_classes), (
        f"train classes {sorted(train_classes)} != test classes {sorted(test_classes)}"
    )

    counts = {}

    # --- test set: copy as-is ---
    for raw_cls, cls in test_classes.items():
        files = list_images(src / "test" / raw_cls)
        copy_all(files, dst / "test" / cls)
        counts[("test", cls)] = len(files)

    # --- train -> train/val, stratified per class ---
    for raw_cls, cls in train_classes.items():
        files = list(list_images(src / "train" / raw_cls))
        random.shuffle(files)
        n_val = round(len(files) * val_fraction)
        val_files, train_files = files[:n_val], files[n_val:]
        copy_all(train_files, dst / "train" / cls)
        copy_all(val_files, dst / "val" / cls)
        counts[("train", cls)] = len(train_files)
        counts[("val", cls)] = len(val_files)

    # --- report ---
    classes = sorted(set(train_classes.values()))
    print(f"\nsrc: {src}\ndst: {dst}\nseed: {seed}   val fraction: {val_fraction}\n")
    print(f"{'split':<8}{'class':<10}{'count':>10}")
    print("-" * 28)
    grand = 0
    for split in ("train", "val", "test"):
        sub = 0
        for cls in classes:
            c = counts[(split, cls)]
            sub += c
            grand += c
            print(f"{split:<8}{cls:<10}{c:>10}")
        print(f"{'':<8}{'(total)':<10}{sub:>10}")
        if len(classes) == 2:
            a, b = classes
            print(f"{'':<8}{a}/{b} ratio: {counts[(split, a)] / counts[(split, b)]:.4f}\n")
        else:
            print()
    print(f"GRAND TOTAL: {grand}")


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--src", type=Path, default=DEFAULT_SRC,
                    help=f"raw download root, containing train/ and test/ (default: {DEFAULT_SRC})")
    ap.add_argument("--dst", type=Path, default=DEFAULT_DST,
                    help=f"output ImageFolder root (default: {DEFAULT_DST})")
    ap.add_argument("--seed", type=int, default=DEFAULT_SEED,
                    help=f"random seed for the train/val split (default: {DEFAULT_SEED})")
    ap.add_argument("--val-fraction", type=float, default=DEFAULT_VAL_FRACTION,
                    help=f"fraction of train/ held out as val (default: {DEFAULT_VAL_FRACTION})")
    args = ap.parse_args()
    restructure(args.src, args.dst, args.seed, args.val_fraction)


if __name__ == "__main__":
    main()

"""# Data Extraction for all files"""

"""
data_loader.py
==============

Reusable PyTorch data-loading utilities for our ImageFolder-structured image
datasets (real vs. AI-generated image detection).

It is **dataset-agnostic**: point it at any folder that follows the convention

    <root>/
        train/<class_a>/*.jpg
              <class_b>/*.png
              ...
        val/  <class_a>/...
              <class_b>/...
        test/ <class_a>/...
              <class_b>/...

and it will work the same way, whether that root is ``./data/dataset`` (CIFAKE),
``./data/sid_set`` (SID_Set), ``./data/wildfake`` (WildFake) or the COCO/DALL-E
demo benchmark. Class names are **inferred from the sub-folder names**, so a
dataset with 2 classes (``real``/``fake``) and one with 3+ classes both work
without code changes.

Under the hood this wraps :class:`torchvision.datasets.ImageFolder` rather than
re-implementing dataset scanning. The only thing we customise is which file
extensions count as images (ImageFolder defaults are fine, but we want an
explicit, configurable allow-list so behaviour is identical across the team's
machines and scripts).

Quick start
-----------
>>> from src.data_loader import build_dataloaders
>>> data = build_dataloaders("./data/dataset", batch_size=64, image_size=32)
>>> data.classes
['fake', 'real']
>>> images, labels = next(iter(data.train_loader))
>>> images.shape
torch.Size([64, 3, 32, 32])

You get back a :class:`DatasetBundle` exposing both the ``DataLoader`` objects
(``.train_loader`` / ``.val_loader`` / ``.test_loader``) and the underlying
``Dataset`` objects (``.train_dataset`` / ...), plus ``.classes`` and
``.class_to_idx``.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Optional, Sequence

import torch
from PIL import Image
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms
from torchvision.datasets import ImageFolder

# --------------------------------------------------------------------------- #
# Defaults
# --------------------------------------------------------------------------- #

#: File extensions treated as images by default. Lower-case, leading dot.
#: Override via the ``extensions`` parameter of :func:`build_dataloaders`.
DEFAULT_EXTENSIONS: tuple[str, ...] = (".jpg", ".jpeg", ".png", ".bmp", ".webp")

#: The three splits we expect under a dataset root.
SPLITS: tuple[str, ...] = ("train", "val", "test")

#: ImageNet channel statistics — the standard normalisation for models
#: pre-trained on ImageNet (ResNet, EfficientNet, ViT, ...). If you train a
#: model from scratch you may prefer per-dataset stats, but these are a safe,
#: widely-used default and keep results comparable across our datasets.
IMAGENET_MEAN: tuple[float, float, float] = (0.485, 0.456, 0.406)
IMAGENET_STD: tuple[float, float, float] = (0.229, 0.224, 0.225)


# --------------------------------------------------------------------------- #
# Image loader
# --------------------------------------------------------------------------- #

def rgb_loader(path: str) -> Image.Image:
    """Open an image file and force it to 3-channel RGB.

    Several of our datasets contain grayscale (1-channel) or RGBA (4-channel)
    images. Converting everything to RGB at load time guarantees the transform
    pipeline always receives a consistent 3-channel image, so downstream tensor
    shapes are always ``(3, H, W)``.
    """
    with Image.open(path) as img:
        return img.convert("RGB")


# --------------------------------------------------------------------------- #
# Transforms
# --------------------------------------------------------------------------- #

def default_transform(
    image_size: int | tuple[int, int] = 224,
    *,
    mean: Sequence[float] = IMAGENET_MEAN,
    std: Sequence[float] = IMAGENET_STD,
) -> transforms.Compose:
    """Build the default (deterministic, no-augmentation) transform pipeline.

    Steps:
      1. ``Resize`` to ``image_size`` (square if an int is given).
      2. ``ToTensor`` — HWC uint8 ``[0, 255]`` PIL image -> CHW float ``[0, 1]``.
      3. ``Normalize`` — subtract ``mean`` and divide by ``std`` per channel.

    RGB conversion is handled by :func:`rgb_loader` before this runs, so it is
    not repeated here.

    Parameters
    ----------
    image_size:
        Target size. ``int`` -> ``(image_size, image_size)``. Tuple -> ``(H, W)``.
    mean, std:
        Per-channel normalisation statistics. Defaults to ImageNet stats.

    Returns
    -------
    torchvision.transforms.Compose
    """
    if isinstance(image_size, int):
        size: tuple[int, int] = (image_size, image_size)
    else:
        size = tuple(image_size)  # type: ignore[assignment]

    return transforms.Compose(
        [
            transforms.Resize(size),
            transforms.ToTensor(),
            transforms.Normalize(mean=list(mean), std=list(std)),
        ]
    )


# --------------------------------------------------------------------------- #
# Result bundle
# --------------------------------------------------------------------------- #

@dataclass
class DatasetBundle:
    """Everything :func:`build_dataloaders` produces, in one object.

    Attributes
    ----------
    train_dataset, val_dataset, test_dataset:
        The underlying :class:`torchvision.datasets.ImageFolder` datasets. Use
        these directly when you need something the DataLoader doesn't give you,
        e.g. computing class weights from ``train_dataset.targets``, or pulling a
        single ``(image_tensor, label)`` sample for inspection.
    train_loader, val_loader, test_loader:
        Batched, ready-to-iterate :class:`torch.utils.data.DataLoader` objects.
        ``train_loader`` is shuffled (unless ``shuffle=False``); the val/test
        loaders never shuffle so evaluation is deterministic.
    classes:
        Class names inferred from the sub-folder names, sorted alphabetically.
        The index of a name in this list is its integer label.
    class_to_idx:
        Mapping ``{class_name: integer_label}``.
    root:
        The dataset root this bundle was built from.
    """

    train_dataset: Dataset
    val_dataset: Dataset
    test_dataset: Dataset
    train_loader: DataLoader
    val_loader: DataLoader
    test_loader: DataLoader
    classes: list[str]
    class_to_idx: dict[str, int]
    root: Path

    # -- convenience accessors ------------------------------------------------

    def datasets(self) -> dict[str, Dataset]:
        """Return ``{"train": ..., "val": ..., "test": ...}`` datasets."""
        return {
            "train": self.train_dataset,
            "val": self.val_dataset,
            "test": self.test_dataset,
        }

    def loaders(self) -> dict[str, DataLoader]:
        """Return ``{"train": ..., "val": ..., "test": ...}`` loaders."""
        return {
            "train": self.train_loader,
            "val": self.val_loader,
            "test": self.test_loader,
        }

    def class_counts(self, split: str = "train") -> dict[str, int]:
        """Count images per class in a split (default ``train``).

        Handy for spotting class imbalance or computing loss weights.
        """
        ds = self.datasets()[split]
        counts = {name: 0 for name in self.classes}
        for target in ds.targets:  # type: ignore[attr-defined]
            counts[self.classes[target]] += 1
        return counts

    def class_weights(self, split: str = "train") -> torch.Tensor:
        """Inverse-frequency class weights for ``nn.CrossEntropyLoss(weight=...)``.

        Weight for class ``c`` is ``total / (num_classes * count[c])`` so weights
        average to ~1.0. Returned in class-index order as a float tensor.
        """
        counts = self.class_counts(split)
        total = sum(counts.values())
        n = len(self.classes)
        return torch.tensor(
            [total / (n * max(counts[name], 1)) for name in self.classes],
            dtype=torch.float,
        )


# --------------------------------------------------------------------------- #
# Main entry point
# --------------------------------------------------------------------------- #

def build_dataloaders(
    root: str | os.PathLike,
    *,
    # --- batching ---------------------------------------------------------
    batch_size: int = 32,
    num_workers: int = 4,
    shuffle: bool = True,
    drop_last: bool = False,
    pin_memory: Optional[bool] = None,
    # --- image pipeline --------------------------------------------------
    image_size: int | tuple[int, int] = 224,
    mean: Sequence[float] = IMAGENET_MEAN,
    std: Sequence[float] = IMAGENET_STD,
    train_transform: Optional[Callable] = None,
    eval_transform: Optional[Callable] = None,
    # --- file handling -------------------------------------------------
    extensions: Sequence[str] = DEFAULT_EXTENSIONS,
    loader: Callable[[str], Image.Image] = rgb_loader,
    # --- reproducibility ---------------------------------------------
    seed: Optional[int] = None,
) -> DatasetBundle:
    """Build train/val/test datasets + dataloaders from an ImageFolder root.

    Parameters
    ----------
    root:
        Dataset root. Must contain ``train/``, ``val/`` and ``test/``
        sub-directories, each holding one sub-folder per class.

    batch_size:
        Number of samples per batch, for every split. (Default 32.)
    num_workers:
        Subprocesses used for data loading. ``0`` loads in the main process
        (simplest, slowest). A good starting value is 4-8. On macOS/Windows the
        worker processes are *spawned*, so any script that builds loaders with
        ``num_workers > 0`` must be guarded by ``if __name__ == "__main__":``
        (this module's ``__main__`` block already is).
    shuffle:
        Whether the **training** loader reshuffles every epoch. Val and test are
        never shuffled. (Default True.)
    drop_last:
        Drop the final partial batch of the training loader. Useful when a model
        component needs a fixed batch size (e.g. some BatchNorm setups).
        Val/test never drop. (Default False.)
    pin_memory:
        Page-lock host memory for faster CPU->GPU transfer. ``None`` (default)
        auto-enables it only when CUDA is available.

    image_size:
        Target size for ``Resize``. ``int`` -> square; ``(H, W)`` tuple -> exact.
        Ignored for any split where you pass your own transform. (Default 224.)
    mean, std:
        Per-channel normalisation stats used by the default transform.
    train_transform:
        Custom torchvision transform (callable ``PIL.Image -> Tensor``) for the
        training split. Pass this to add augmentation (RandomHorizontalFlip,
        RandomResizedCrop, ...). When ``None``, the deterministic
        :func:`default_transform` is used.
    eval_transform:
        Custom transform for the val and test splits. When ``None``, the
        deterministic :func:`default_transform` is used. Keep this
        augmentation-free so evaluation is repeatable.

    extensions:
        Allowed image file extensions (lower-case, leading dot). Files with any
        other extension are ignored. Defaults to
        ``('.jpg', '.jpeg', '.png', '.bmp', '.webp')``.
    loader:
        Callable ``path -> PIL.Image``. Defaults to :func:`rgb_loader`, which
        forces RGB. Override only if you need a different decode behaviour.

    seed:
        If given, the training loader shuffles via a seeded
        ``torch.Generator`` so epoch-to-epoch ordering is reproducible across
        runs. Does not touch the global RNG.

    Returns
    -------
    DatasetBundle
        Datasets, loaders, and inferred class metadata. See that class's
        docstring.

    Raises
    ------
    FileNotFoundError
        If ``root`` or any of ``train`` / ``val`` / ``test`` is missing.
    ValueError
        If a split has no images, or the splits disagree on the class list.
    """
    root = Path(root).expanduser().resolve()
    if not root.is_dir():
        raise FileNotFoundError(f"Dataset root does not exist: {root}")

    # Normalise the extension allow-list to a lower-case set for O(1) lookup.
    ext_set = {e.lower() if e.startswith(".") else f".{e.lower()}" for e in extensions}

    def is_valid_file(path: str) -> bool:
        """Extension filter handed to ImageFolder (replaces its default list)."""
        return Path(path).suffix.lower() in ext_set

    if pin_memory is None:
        pin_memory = torch.cuda.is_available()

    # Resolve transforms once; the same eval transform object is shared by
    # val and test (both deterministic, so sharing is safe).
    train_tf = train_transform or default_transform(image_size, mean=mean, std=std)
    eval_tf = eval_transform or default_transform(image_size, mean=mean, std=std)
    split_tf = {"train": train_tf, "val": eval_tf, "test": eval_tf}

    # --- build one ImageFolder per split ---------------------------------
    datasets: dict[str, ImageFolder] = {}
    for split in SPLITS:
        split_dir = root / split
        if not split_dir.is_dir():
            raise FileNotFoundError(
                f"Expected split folder '{split}' under {root} "
                f"(looked for {split_dir})."
            )
        ds = ImageFolder(
            root=str(split_dir),
            transform=split_tf[split],
            loader=loader,
            is_valid_file=is_valid_file,  # our configurable extension filter
        )
        if len(ds) == 0:
            raise ValueError(
                f"Split '{split}' at {split_dir} contains no files matching "
                f"extensions {sorted(ext_set)}."
            )
        datasets[split] = ds

    # --- sanity-check that all splits share the same classes ------------
    class_lists = {split: ds.classes for split, ds in datasets.items()}
    reference = class_lists["train"]
    mismatched = {s: c for s, c in class_lists.items() if c != reference}
    if mismatched:
        raise ValueError(
            "Splits disagree on class folders.\n"
            + "\n".join(f"  {s}: {c}" for s, c in class_lists.items())
            + "\nEvery split must contain the same set of class sub-folders."
        )

    # --- wrap each dataset in a DataLoader ------------------------------
    generator: Optional[torch.Generator] = None
    if seed is not None:
        generator = torch.Generator()
        generator.manual_seed(seed)

    # num_workers > 0 benefits from keeping workers alive between epochs.
    persistent_workers = num_workers > 0

    def make_loader(split: str, *, do_shuffle: bool, do_drop_last: bool) -> DataLoader:
        return DataLoader(
            datasets[split],
            batch_size=batch_size,
            shuffle=do_shuffle,
            num_workers=num_workers,
            pin_memory=pin_memory,
            drop_last=do_drop_last,
            persistent_workers=persistent_workers,
            generator=generator if do_shuffle else None,
        )

    train_loader = make_loader("train", do_shuffle=shuffle, do_drop_last=drop_last)
    val_loader = make_loader("val", do_shuffle=False, do_drop_last=False)
    test_loader = make_loader("test", do_shuffle=False, do_drop_last=False)

    return DatasetBundle(
        train_dataset=datasets["train"],
        val_dataset=datasets["val"],
        test_dataset=datasets["test"],
        train_loader=train_loader,
        val_loader=val_loader,
        test_loader=test_loader,
        classes=list(reference),
        class_to_idx=dict(datasets["train"].class_to_idx),
        root=root,
    )


# --------------------------------------------------------------------------- #
# Usage example / smoke test
# --------------------------------------------------------------------------- #

if __name__ == "__main__":
    # Points at the CIFAKE dataset we built at ./data/dataset. Change this path
    # (or pass your own) to run against SID_Set, WildFake, etc.
    import argparse

    parser = argparse.ArgumentParser(description="Smoke-test the data loader.")
    parser.add_argument(
        "root",
        nargs="?",
        default="./data/dataset",
        help="Dataset root (default: ./data/dataset, our CIFAKE folder)",
    )
    parser.add_argument("--batch-size", type=int, default=64)
    parser.add_argument("--image-size", type=int, default=32,
                        help="CIFAKE images are 32x32; default 32 here")
    parser.add_argument("--num-workers", type=int, default=2)
    args = parser.parse_args()

    data = build_dataloaders(
        args.root,
        batch_size=args.batch_size,
        image_size=args.image_size,
        num_workers=args.num_workers,
        seed=42,
    )

    print(f"\nDataset root : {data.root}")
    print(f"Inferred classes : {data.classes}")
    print(f"class_to_idx     : {data.class_to_idx}")

    print(f"\n{'split':<8}{'images':>10}{'batches':>10}   per-class counts")
    print("-" * 60)
    for split, ds in data.datasets().items():
        loader = data.loaders()[split]
        counts = data.class_counts(split)
        counts_str = ", ".join(f"{k}={v}" for k, v in counts.items())
        print(f"{split:<8}{len(ds):>10,}{len(loader):>10,}   {counts_str}")

    # Pull one batch from the training loader to confirm tensor shapes.
    images, labels = next(iter(data.train_loader))
    print(
        f"\nSample train batch: images={tuple(images.shape)} "
        f"dtype={images.dtype}, labels={tuple(labels.shape)}"
    )
    print(f"pixel range after normalise: [{images.min():.3f}, {images.max():.3f}]")
    print(f"inverse-frequency class weights (train): {data.class_weights().tolist()}")