# -*- coding: utf-8 -*-
"""evaluations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1apJ9NyM9f1RjJQ-zvZr4AfLORYWTqv98

# EfficientNet-B0 Robustness Evaluation

This notebook evaluates four independently trained EfficientNet-B0 models:

- `none`
- `continuous`
- `heldout`
- `spec`

## Evaluation protocol

All four models are evaluated using:

1. The same unseen test images.
2. The same locked robustness evaluation suite.
3. The same preprocessing pipeline.
4. The same classification threshold of 0.5.
5. The same evaluation metrics.

The evaluation grid was fixed before final test-set evaluation and must not
be changed after observing test results.

The `spec` model was trained using the exact evaluation severity points,
whereas the `heldout` model was trained while excluding neighbourhoods
around these severity points. Therefore, `heldout` performance is used to
assess generalisation to unseen severity levels, while `spec` acts as a
train-on-evaluation-condition comparison.

## Test-set independence

`TEST_ROOT` must contain images that were not used for model training,
validation, augmentation-policy selection, checkpoint selection, or
evaluation-grid selection.

The final test set is used only for final model comparison.
"""

!git clone https://github.com/TechJammers-26/AI-Image-Detection.git

# ============================================================
# CELL 2: IMPORT LIBRARIES
# ============================================================

import os
import sys
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import matplotlib.pyplot as plt

from PIL import Image

from torch.utils.data import Dataset, DataLoader
from torchvision import models, transforms

from sklearn.metrics import (
    roc_auc_score,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score
)

from scipy.stats import binomtest

# ============================================================
# CELL 3: DEVICE SETUP
# ============================================================
# Use GPU if one is available.
# Otherwise, evaluation will run on CPU.

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Device:", device)

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

# ============================================================
# CELL 4: MOUNT GOOGLE DRIVE
# ============================================================
# Mount Google Drive so that the notebook can access:
# - the saved model checkpoints
# - augmentations.py
# - the test dataset

from google.colab import drive

drive.mount("/content/drive", force_remount=True)

# ============================================================
# CELL 5: PROJECT PATHS
# ============================================================
# Replace these paths with the real project locations before
# submitting or sharing the notebook.

PROJECT_ROOT = "/content/drive/MyDrive/TikTok TechJam" ##remind me to change

CHECKPOINTS = {
    "none": os.path.join(
        PROJECT_ROOT,
        "checkpoints",
        "efficientnet_b0_none_best.pth"
    ),

    "continuous": os.path.join(
        PROJECT_ROOT,
        "checkpoints",
        "efficientnet_b0_continuous_best.pth"
    ),

    "heldout": os.path.join(
        PROJECT_ROOT,
        "checkpoints",
        "efficientnet_b0_heldout_best.pth"
    ),

    "spec": os.path.join(
        PROJECT_ROOT,
        "checkpoints",
        "efficientnet_b0_spec_best.pth"
    ),
}

RESULTS_DIR = os.path.join(
    PROJECT_ROOT,
    "evaluation_results"
)

os.makedirs(
    RESULTS_DIR,
    exist_ok=True
)

BATCH_SIZE = 64
NUM_WORKERS = 2

# Define the local directory where the dataset will be stored and unzipped
GOOGLE_DRIVE_DATASET_PATH = '/content/drive/MyDrive/TikTok TechJam/dataset' #same thing rmb to change
DATASET_DIR = '/content/dataset'
os.makedirs(DATASET_DIR, exist_ok=True)

# List of zip file names to process from GOOGLE_DRIVE_DATASET_PATH
ZIP_FILE_NAMES = [
    'sid_clean.zip',
    'cifake_clean.zip',
    'wildfake_clean.zip'
]

TRAIN_ROOT = os.path.join(DATASET_DIR, "train")
VAL_ROOT = os.path.join(DATASET_DIR, "val")
TEST_ROOT = os.path.join(DATASET_DIR, "test")

print(f"TRAIN_ROOT set to: {TRAIN_ROOT}")
print(f"VAL_ROOT set to: {VAL_ROOT}")
print(f"TEST_ROOT set to: {TEST_ROOT}")

import zipfile

print(f"Starting dataset extraction to: {DATASET_DIR}")

for zip_file_name in ZIP_FILE_NAMES:
    # Construct the full path to the zip file in Google Drive
    google_drive_zip_path = os.path.join(GOOGLE_DRIVE_DATASET_PATH, zip_file_name)

    # Define a temporary path for the zip file in the Colab environment
    temp_zip_path = os.path.join('/content', zip_file_name)

    print(f"Copying {zip_file_name} from Google Drive...")
    # Copy the zip file from Google Drive to the Colab environment
    !cp "{google_drive_zip_path}" "{temp_zip_path}"
    print(f"Copied {zip_file_name} to {temp_zip_path}")

    print(f"Unzipping {zip_file_name}...")
    # Unzip the file into the DATASET_DIR
    with zipfile.ZipFile(temp_zip_path, 'r') as zip_ref:
        zip_ref.extractall(DATASET_DIR)
    print(f"Unzipped {zip_file_name} to {DATASET_DIR}")

    # Remove the temporary zip file to save space
    os.remove(temp_zip_path)
    print(f"Removed temporary zip file: {temp_zip_path}")

print("All datasets extracted successfully!")

##ONLY FOR ME TO RUN CUS MY TEST FOLDER = False!!!!!!!!!!!!!!!!!!!!!!!

# import os
# import shutil

# # Define the target consolidated directories
# CONSOLIDATED_TRAIN_ROOT = os.path.join(DATASET_DIR, "train")
# CONSOLIDATED_VAL_ROOT = os.path.join(DATASET_DIR, "val")
# CONSOLIDATED_TEST_ROOT = os.path.join(DATASET_DIR, "test")

# split_roots = {
#     'train': CONSOLIDATED_TRAIN_ROOT,
#     'val': CONSOLIDATED_VAL_ROOT,
#     'test': CONSOLIDATED_TEST_ROOT,
# }

# # Create the consolidated root directories
# for root in split_roots.values():
#     os.makedirs(os.path.join(root, "real"), exist_ok=True)
#     os.makedirs(os.path.join(root, "ai"), exist_ok=True)

# # List of unzipped dataset base directories
# UNZIPPED_DATASET_DIRS = [
#     os.path.join(DATASET_DIR, 'sid_clean'),
#     os.path.join(DATASET_DIR, 'cifake_dataset_clean'),
#     os.path.join(DATASET_DIR, 'wildfake_clean')
# ]

# print("Consolidating datasets...")

# total_moved = 0
# total_errors = 0

# for dataset_base_dir in UNZIPPED_DATASET_DIRS:
#     dataset_name = os.path.basename(dataset_base_dir)
#     print(f"\nProcessing dataset: {dataset_base_dir}")

#     if not os.path.exists(dataset_base_dir):
#         print(f"  ERROR: dataset directory does not exist, skipping entirely: {dataset_base_dir}")
#         total_errors += 1
#         continue

#     for split in ['train', 'val', 'test']:
#         source_split_dir = os.path.join(dataset_base_dir, split)

#         if not os.path.exists(source_split_dir):
#             print(f"  WARNING: no '{split}' split found for {dataset_name}, skipping this split.")
#             continue

#         target_real_dir = os.path.join(split_roots[split], 'real')
#         target_ai_dir = os.path.join(split_roots[split], 'ai')

#         # ---- real ----
#         source_real_dir = os.path.join(source_split_dir, 'real')
#         if os.path.exists(source_real_dir):
#             files = os.listdir(source_real_dir)
#             if len(files) == 0:
#                 print(f"  WARNING: {source_real_dir} exists but is empty.")
#             moved = 0
#             for filename in files:
#                 src_path = os.path.join(source_real_dir, filename)
#                 if not os.path.isfile(src_path):
#                     continue
#                 new_name = f"{dataset_name}_{filename}"
#                 dst_path = os.path.join(target_real_dir, new_name)
#                 if os.path.exists(dst_path):
#                     print(f"    ERROR: collision, skipping: {new_name}")
#                     total_errors += 1
#                     continue
#                 try:
#                     shutil.move(src_path, dst_path)
#                     moved += 1
#                 except Exception as e:
#                     print(f"    ERROR moving {src_path}: {e}")
#                     total_errors += 1
#             print(f"  Moved {moved} real images: {source_real_dir} -> {target_real_dir}")
#             total_moved += moved
#         else:
#             print(f"  WARNING: no 'real' folder in {dataset_name}/{split}.")

#         # ---- fake (-> ai) ----
#         source_fake_dir = os.path.join(source_split_dir, 'fake')
#         if os.path.exists(source_fake_dir):
#             files = os.listdir(source_fake_dir)
#             if len(files) == 0:
#                 print(f"  WARNING: {source_fake_dir} exists but is empty.")
#             moved = 0
#             for filename in files:
#                 src_path = os.path.join(source_fake_dir, filename)
#                 if not os.path.isfile(src_path):
#                     continue
#                 new_name = f"{dataset_name}_{filename}"
#                 dst_path = os.path.join(target_ai_dir, new_name)
#                 if os.path.exists(dst_path):
#                     print(f"    ERROR: collision, skipping: {new_name}")
#                     total_errors += 1
#                     continue
#                 try:
#                     shutil.move(src_path, dst_path)
#                     moved += 1
#                 except Exception as e:
#                     print(f"    ERROR moving {src_path}: {e}")
#                     total_errors += 1
#             print(f"  Moved {moved} fake images: {source_fake_dir} -> {target_ai_dir} (as ai)")
#             total_moved += moved
#         else:
#             print(f"  WARNING: no 'fake' folder in {dataset_name}/{split}.")

# print(f"\nTotal images moved: {total_moved}")
# print(f"Total errors: {total_errors}")

# if total_errors > 0:
#     print("\n!! Errors occurred during consolidation. Review the log above before deleting source folders. !!")

# print("Dataset consolidation complete!")

# # Re-run the ROOT definitions after consolidation
# TRAIN_ROOT = CONSOLIDATED_TRAIN_ROOT
# VAL_ROOT = CONSOLIDATED_VAL_ROOT
# TEST_ROOT = CONSOLIDATED_TEST_ROOT
# print(f"TRAIN_ROOT re-set to: {TRAIN_ROOT}")
# print(f"VAL_ROOT re-set to: {VAL_ROOT}")
# print(f"TEST_ROOT re-set to: {TEST_ROOT}")

print("Test folder exists:", os.path.exists(TEST_ROOT))

for policy, path in CHECKPOINTS.items():
    print(
        f"{policy:12s}",
        os.path.exists(path),
        path
    )

# ============================================================
# CELL 6: IMPORT AUGMENTATION FUNCTIONS
# ============================================================
# Add the project folder to Python's import path so that
# augmentations.py can be imported.

# Connect to Repo for Augmentation functions

REPO_PATH = "/content/AI-Image-Detection/src/aigcdet"

if REPO_PATH not in sys.path:
    sys.path.append(REPO_PATH)

from augmentations import (
    build_train_augment,
    apply_eval_transform,
    eval_names,
    get_eval_transform,
    canonicalize,
    EVAL_SUITE
)

print("augmentations.py imported successfully!")

# ============================================================
# CELL 7: VERIFY LOCKED EVALUATION SUITE
# ============================================================

print(
    "Number of evaluation conditions:",
    len(EVAL_SUITE)
)

print()

for i, spec in enumerate(
    EVAL_SUITE,
    start=1
):

    print(
        f"{i:02d}. "
        f"{spec.name:28s} | "
        f"Family: {spec.family:8s} | "
        f"{spec.label}"
    )

# ============================================================
# CELL 8: MODEL INPUT TRANSFORMATION
# ============================================================
# EfficientNet-B0 expects 224 x 224 inputs.
#
# Images are converted to tensors and normalized using
# ImageNet mean and standard deviation because the model
# was initialized from ImageNet-pretrained EfficientNet-B0.

model_transform = transforms.Compose([
    transforms.Resize((224, 224)),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

# # ============================================================
# # CELL 9: BUILD TEST FILE LIST ONCE
# # ============================================================
# # Directory scanning is performed only once.
# #
# # Every robustness condition and every model will use the
# # exact same ordered list of test images.

# def build_test_samples(root_dir):

#     class_mapping = {
#         "real": 0,
#         "ai": 1
#     }

#     valid_extensions = (
#         ".jpg",
#         ".jpeg",
#         ".png",
#         ".webp",
#         ".bmp"
#     )

#     samples = []

#     for class_name, label in class_mapping.items():

#         class_dir = os.path.join(
#             root_dir,
#             class_name
#         )

#         if not os.path.isdir(class_dir):
#             raise FileNotFoundError(
#                 f"Missing class directory: {class_dir}"
#             )

#         for current_dir, _, filenames in os.walk(
#             class_dir
#         ):

#             for filename in sorted(filenames):

#                 if filename.lower().endswith(
#                     valid_extensions
#                 ):

#                     filepath = os.path.join(
#                         current_dir,
#                         filename
#                     )

#                     image_key = os.path.relpath(
#                         filepath,
#                         root_dir
#                     )

#                     samples.append({
#                         "filepath": filepath,
#                         "label": label,
#                         "image_key": image_key
#                     })

#     # Sorting ensures deterministic image ordering.
#     samples = sorted(
#         samples,
#         key=lambda x: x["image_key"]
#     )

#     return samples


# TEST_SAMPLES = build_test_samples(
#     TEST_ROOT
# )

# print(
#     "Total test images:",
#     len(TEST_SAMPLES)
# )

"""### Data Consolidation

The `FileNotFoundError` for `/content/dataset/test/real` indicates that the datasets were unzipped into separate subdirectories (e.g., `sid_clean`, `cifake_dataset_clean`, `wildfake_clean`) under `/content/dataset`, and each of these might contain their own `train`, `val`, and `test` splits. To correctly build the `TEST_SAMPLES` list for evaluation, we need to consolidate all images from these individual splits into a single, unified `train`, `val`, and `test` directory structure directly under `/content/dataset`.
"""

# Let's inspect the contents of DATASET_DIR to confirm the structure after unzipping.
print(f"Contents of {DATASET_DIR}:")
!ls -F "{DATASET_DIR}"

# Also check inside one of the unzipped folders, e.g., sid_clean
print(f"\nContents of {DATASET_DIR}/sid_clean (if it exists):")
!ls -F "{DATASET_DIR}/sid_clean"

import shutil

# Define the target consolidated directories
CONSOLIDATED_TRAIN_ROOT = os.path.join(DATASET_DIR, "train")
CONSOLIDATED_VAL_ROOT = os.path.join(DATASET_DIR, "val")
CONSOLIDATED_TEST_ROOT = os.path.join(DATASET_DIR, "test")

split_roots = {
    'train': CONSOLIDATED_TRAIN_ROOT,
    'val': CONSOLIDATED_VAL_ROOT,
    'test': CONSOLIDATED_TEST_ROOT,
}

# Create the consolidated root directories
for root in split_roots.values():
    os.makedirs(os.path.join(root, "real"), exist_ok=True)
    os.makedirs(os.path.join(root, "ai"), exist_ok=True)

# List of unzipped dataset base directories (adjust based on actual unzipped folder names)
UNZIPPED_DATASET_DIRS = [
    os.path.join(DATASET_DIR, 'sid_clean'),
    os.path.join(DATASET_DIR, 'cifake_dataset_clean'), # This might be named 'cifake_clean' or similar
    os.path.join(DATASET_DIR, 'wildfake_clean')
]

print("Consolidating datasets...")

total_moved = 0
total_errors = 0

for dataset_base_dir in UNZIPPED_DATASET_DIRS:
    dataset_name = os.path.basename(dataset_base_dir)
    print(f"\nProcessing dataset: {dataset_base_dir}")

    if not os.path.exists(dataset_base_dir):
        print(f"  ERROR: dataset directory does not exist, skipping entirely: {dataset_base_dir}")
        total_errors += 1
        continue

    for split in ['train', 'val', 'test']:
        source_split_dir = os.path.join(dataset_base_dir, split)

        if not os.path.exists(source_split_dir):
            print(f"  WARNING: no '{split}' split found for {dataset_name}, skipping this split.")
            continue

        target_real_dir = os.path.join(split_roots[split], 'real')
        target_ai_dir = os.path.join(split_roots[split], 'ai')

        # Real images
        source_real_dir = os.path.join(source_split_dir, 'real')
        if os.path.exists(source_real_dir):
            files = os.listdir(source_real_dir)
            if len(files) == 0:
                print(f"  WARNING: {source_real_dir} exists but is empty.")
            moved = 0
            for filename in files:
                src_path = os.path.join(source_real_dir, filename)
                if not os.path.isfile(src_path):
                    continue
                new_name = f"{dataset_name}_{filename}"
                dst_path = os.path.join(target_real_dir, new_name)
                if os.path.exists(dst_path):
                    print(f"    ERROR: collision, skipping: {new_name}")
                    total_errors += 1
                    continue
                try:
                    shutil.move(src_path, dst_path)
                    moved += 1
                except Exception as e:
                    print(f"    ERROR moving {src_path}: {e}")
                    total_errors += 1
            print(f"  Moved {moved} real images: {source_real_dir} -> {target_real_dir}")
            total_moved += moved
        else:
            print(f"  WARNING: no 'real' folder in {dataset_name}/{split}.")

        # Fake (AI) images
        source_fake_dir = os.path.join(source_split_dir, 'fake')
        if os.path.exists(source_fake_dir):
            files = os.listdir(source_fake_dir)
            if len(files) == 0:
                print(f"  WARNING: {source_fake_dir} exists but is empty.")
            moved = 0
            for filename in files:
                src_path = os.path.join(source_fake_dir, filename)
                if not os.path.isfile(src_path):
                    continue
                new_name = f"{dataset_name}_{filename}"
                dst_path = os.path.join(target_ai_dir, new_name)
                if os.path.exists(dst_path):
                    print(f"    ERROR: collision, skipping: {new_name}")
                    total_errors += 1
                    continue
                try:
                    shutil.move(src_path, dst_path)
                    moved += 1
                except Exception as e:
                    print(f"    ERROR moving {src_path}: {e}")
                    total_errors += 1
            print(f"  Moved {moved} fake images: {source_fake_dir} -> {target_ai_dir} (as ai)")
            total_moved += moved
        else:
            print(f"  WARNING: no 'fake' folder in {dataset_name}/{split}.")

print(f"\nTotal images moved: {total_moved}")
print(f"Total errors: {total_errors}")

if total_errors > 0:
    print("\n!! Errors occurred during consolidation. Review the log above before proceeding. !!")

print("Dataset consolidation complete!")

# Re-run the ROOT definitions after consolidation to update them to the consolidated paths
TRAIN_ROOT = CONSOLIDATED_TRAIN_ROOT
VAL_ROOT = CONSOLIDATED_VAL_ROOT
TEST_ROOT = CONSOLIDATED_TEST_ROOT
print(f"TRAIN_ROOT re-set to: {TRAIN_ROOT}")
print(f"VAL_ROOT re-set to: {VAL_ROOT}")
print(f"TEST_ROOT re-set to: {TEST_ROOT}")

"""The datasets have now been consolidated into unified `train`, `val`, and `test` directories. Now, let's re-build the `TEST_SAMPLES` list using the updated `TEST_ROOT`."""

# Re-run the TEST_SAMPLES building with the consolidated TEST_ROOT
TEST_SAMPLES = build_test_samples(
    TEST_ROOT
)

print(
    "Total test images (after consolidation):",
    len(TEST_SAMPLES)
)

# Verify test folder existence again after consolidation
print("Test folder exists (after consolidation):", os.path.exists(TEST_ROOT))

# ============================================================
# CELL 10: TEST-SET CLASS DISTRIBUTION
# ============================================================

test_labels = [
    sample["label"]
    for sample in TEST_SAMPLES
]

unique, counts = np.unique(
    test_labels,
    return_counts=True
)

class_counts = dict(
    zip(unique, counts)
)

print(
    "Test class counts:",
    class_counts
)

print("0 = Real")
print("1 = AI")

# ============================================================
# CELL 11: ROBUSTNESS TEST DATASET
# ============================================================
# The same test samples are reused across every policy and
# robustness condition.
#
# Returns image_key so predictions from different models can
# later be paired on exactly the same test images.

class RobustnessTestDataset(Dataset):

    def __init__(
        self,
        samples,
        eval_condition
    ):

        self.samples = samples
        self.eval_condition = eval_condition

    def __len__(self):

        return len(self.samples)

    def __getitem__(self, idx):

        sample = self.samples[idx]

        filepath = sample["filepath"]
        label = sample["label"]
        image_key = sample["image_key"]

        image = Image.open(
            filepath
        ).convert("RGB")

        # Apply common canonicalization first.
        image = canonicalize(
            image,
            max_side=512,
            jpeg_quality=95
        )

        # Apply one locked deterministic robustness condition.
        image = apply_eval_transform(
            image,
            name=self.eval_condition,
            image_key=image_key
        )

        # Prepare image for EfficientNet-B0.
        image = model_transform(
            image
        )

        label = torch.tensor(
            label,
            dtype=torch.float32
        )

        return (
            image,
            label,
            image_key
        )

print("EVAL_SUITE type:", type(EVAL_SUITE))
print("EVAL_SUITE:", EVAL_SUITE)

# ============================================================
# CELL 12: CREATE EVALUATION LOADERS
# ============================================================
# Create one DataLoader for every locked evaluation condition.
#
# EVAL_SUITE contains TransformSpec objects.
# We use spec.name as the dictionary key because it is a
# simple string such as:
#   "clean"
#   "jpeg_q70"
#   "blur_s1.0"
#
# These same loaders are reused for all four model policies.

TEST_LOADERS = {}

for spec in EVAL_SUITE:

    condition_name = spec.name

    dataset = RobustnessTestDataset(
        TEST_SAMPLES,
        condition_name
    )

    TEST_LOADERS[condition_name] = DataLoader(
        dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        num_workers=NUM_WORKERS,
        pin_memory=True
    )

print(
    "Created loaders for",
    len(TEST_LOADERS),
    "evaluation conditions."
)

# ============================================================
# CELL 13: EFFICIENTNET-B0 ARCHITECTURE
# ============================================================

def build_model():

    model = models.efficientnet_b0(
        weights=None
    )

    in_features = (
        model.classifier[1].in_features
    )

    model.classifier[1] = nn.Linear(
        in_features,
        1
    )

    return model

# ============================================================
# CELL 14: LOSS FUNCTION
# ============================================================

criterion = nn.BCEWithLogitsLoss()

# ============================================================
# CELL 15: MODEL EVALUATION FUNCTION
# ============================================================
# Returns:
#
# 1. Aggregate metrics
# 2. Per-image predictions
#
# Per-image outputs are retained because all four policies are
# evaluated on the same images. This allows paired statistical
# comparisons between models.

def evaluate_model(
    model,
    loader,
    criterion,
    device
):

    model.eval()

    running_loss = 0.0
    total_samples = 0

    labels_all = []
    probabilities_all = []
    predictions_all = []
    image_keys_all = []

    with torch.no_grad():

        for images, labels, image_keys in loader:

            images = images.to(
                device,
                non_blocking=True
            )

            labels = labels.float().to(
                device,
                non_blocking=True
            )

            logits = model(
                images
            ).squeeze(1)

            loss = criterion(
                logits,
                labels
            )

            probabilities = torch.sigmoid(
                logits
            )

            predictions = (
                probabilities >= 0.5
            ).long()

            batch_size = labels.size(0)

            running_loss += (
                loss.item() * batch_size
            )

            total_samples += batch_size

            labels_all.extend(
                labels.cpu().numpy()
            )

            probabilities_all.extend(
                probabilities.cpu().numpy()
            )

            predictions_all.extend(
                predictions.cpu().numpy()
            )

            image_keys_all.extend(
                list(image_keys)
            )

    labels_all = np.asarray(
        labels_all,
        dtype=int
    )

    probabilities_all = np.asarray(
        probabilities_all
    )

    predictions_all = np.asarray(
        predictions_all,
        dtype=int
    )

    average_loss = (
        running_loss / total_samples
    )

    accuracy = np.mean(
        predictions_all == labels_all
    )

    auc = roc_auc_score(
        labels_all,
        probabilities_all
    )

    precision = precision_score(
        labels_all,
        predictions_all,
        zero_division=0
    )

    recall = recall_score(
        labels_all,
        predictions_all,
        zero_division=0
    )

    f1 = f1_score(
        labels_all,
        predictions_all,
        zero_division=0
    )

    metrics = {
        "loss": average_loss,
        "accuracy": accuracy,
        "auc": auc,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

    predictions_df = pd.DataFrame({
        "image_key": image_keys_all,
        "label": labels_all,
        "probability": probabilities_all,
        "prediction": predictions_all
    })

    return metrics, predictions_df

# ============================================================
# CELL 16: LOAD TRAINED CHECKPOINT
# ============================================================

def load_checkpoint_model(
    checkpoint_path,
    device
):

    model = build_model()

    checkpoint = torch.load(
        checkpoint_path,
        map_location=device,
        weights_only=False
    )

    if (
        isinstance(checkpoint, dict)
        and "model_state_dict" in checkpoint
    ):

        model.load_state_dict(
            checkpoint["model_state_dict"]
        )

    else:

        model.load_state_dict(
            checkpoint
        )

    model = model.to(
        device
    )

    model.eval()

    return model, checkpoint

# ============================================================
# CELL 17: CHECKPOINT VERIFICATION
# ============================================================
# Fail-fast step before performing the expensive full
# robustness evaluation.

for policy, checkpoint_path in CHECKPOINTS.items():

    print(
        "\n" + "=" * 60
    )

    print(
        f"Checking {policy}"
    )

    model, checkpoint = load_checkpoint_model(
        checkpoint_path,
        device
    )

    print(
        "Checkpoint loaded successfully."
    )

    if isinstance(checkpoint, dict):

        if "epoch" in checkpoint:
            print(
                "Saved best epoch:",
                checkpoint["epoch"]
            )

        if "val_accuracy" in checkpoint:
            print(
                "Saved validation accuracy:",
                checkpoint["val_accuracy"]
            )

        if "val_auc" in checkpoint:
            print(
                "Saved validation AUC:",
                checkpoint["val_auc"]
            )

    del model

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

# ============================================================
# CELL 18: FINAL LOCKED TEST-SET EVALUATION
# ============================================================
# All four independently trained policies are evaluated against
# exactly the same locked robustness conditions and exactly the
# same unseen test images.
#
# The evaluation suite must NOT be changed based on the results.

aggregate_results = []
per_image_results = []

for policy, checkpoint_path in CHECKPOINTS.items():

    print(
        "\n" + "=" * 70
    )

    print(
        f"EVALUATING: {policy.upper()}"
    )

    print(
        "=" * 70
    )

    model, checkpoint = load_checkpoint_model(
        checkpoint_path,
        device
    )

    for condition, loader in TEST_LOADERS.items():

        print(
            f"{condition:30s}",
            end=" "
        )

        metrics, predictions_df = evaluate_model(
            model,
            loader,
            criterion,
            device
        )

        aggregate_results.append({
            "policy": policy,
            "condition": condition,
            **metrics
        })

        predictions_df[
            "policy"
        ] = policy

        predictions_df[
            "condition"
        ] = condition

        per_image_results.append(
            predictions_df
        )

        print(
            f"Acc={metrics['accuracy']:.4f} | "
            f"AUC={metrics['auc']:.4f} | "
            f"F1={metrics['f1']:.4f}"
        )

    del model

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

# ============================================================
# CELL 19: SAVE RAW EVALUATION RESULTS
# ============================================================

results_df = pd.DataFrame(
    aggregate_results
)

predictions_df = pd.concat(
    per_image_results,
    ignore_index=True
)

results_df.to_csv(
    os.path.join(
        RESULTS_DIR,
        "aggregate_test_results.csv"
    ),
    index=False
)

predictions_df.to_csv(
    os.path.join(
        RESULTS_DIR,
        "per_image_predictions.csv"
    ),
    index=False
)

print("Results saved.")
print()
display(results_df)

# ============================================================
# CELL 20: ACCURACY ROBUSTNESS MATRIX
# ============================================================

POLICY_ORDER = [
    "none",
    "continuous",
    "heldout",
    "spec"
]

accuracy_matrix = results_df.pivot(
    index="condition",
    columns="policy",
    values="accuracy"
)

accuracy_matrix = accuracy_matrix[
    POLICY_ORDER
]

display(
    accuracy_matrix.round(4)
)

# ============================================================
# CELL 21: ROC-AUC ROBUSTNESS MATRIX
# ============================================================

auc_matrix = results_df.pivot(
    index="condition",
    columns="policy",
    values="auc"
)

auc_matrix = auc_matrix[
    POLICY_ORDER
]

display(
    auc_matrix.round(4)
)

# ============================================================
# CELL 22: ACCURACY ROBUSTNESS HEATMAP
# ============================================================

fig, ax = plt.subplots(
    figsize=(9, 10)
)

image = ax.imshow(
    accuracy_matrix.values,
    aspect="auto"
)

ax.set_xticks(
    np.arange(len(accuracy_matrix.columns))
)

ax.set_xticklabels(
    accuracy_matrix.columns
)

ax.set_yticks(
    np.arange(len(accuracy_matrix.index))
)

ax.set_yticklabels(
    accuracy_matrix.index
)

ax.set_xlabel(
    "Training Augmentation Policy"
)

ax.set_ylabel(
    "Test Robustness Condition"
)

ax.set_title(
    "Accuracy Robustness Matrix"
)

# Add values inside cells.
for i in range(
    accuracy_matrix.shape[0]
):

    for j in range(
        accuracy_matrix.shape[1]
    ):

        ax.text(
            j,
            i,
            f"{accuracy_matrix.iloc[i, j]:.3f}",
            ha="center",
            va="center"
        )

fig.colorbar(
    image,
    ax=ax,
    label="Accuracy"
)

plt.tight_layout()
plt.show()

# ============================================================
# CELL 23: ROC-AUC ROBUSTNESS HEATMAP
# ============================================================

fig, ax = plt.subplots(
    figsize=(9, 10)
)

image = ax.imshow(
    auc_matrix.values,
    aspect="auto"
)

ax.set_xticks(
    np.arange(len(auc_matrix.columns))
)

ax.set_xticklabels(
    auc_matrix.columns
)

ax.set_yticks(
    np.arange(len(auc_matrix.index))
)

ax.set_yticklabels(
    auc_matrix.index
)

ax.set_xlabel(
    "Training Augmentation Policy"
)

ax.set_ylabel(
    "Test Robustness Condition"
)

ax.set_title(
    "ROC-AUC Robustness Matrix"
)

for i in range(
    auc_matrix.shape[0]
):

    for j in range(
        auc_matrix.shape[1]
    ):

        ax.text(
            j,
            i,
            f"{auc_matrix.iloc[i, j]:.3f}",
            ha="center",
            va="center"
        )

fig.colorbar(
    image,
    ax=ax,
    label="ROC-AUC"
)

plt.tight_layout()
plt.show()

# ============================================================
# CELL 24: PRECISION & RECALL ROBUSTNESS MATRICES
# ============================================================

precision_matrix = results_df.pivot(
    index="condition",
    columns="policy",
    values="precision"
)

precision_matrix = precision_matrix[
    POLICY_ORDER
]

recall_matrix = results_df.pivot(
    index="condition",
    columns="policy",
    values="recall"
)

recall_matrix = recall_matrix[
    POLICY_ORDER
]

display(
    precision_matrix.round(4)
)

display(
    recall_matrix.round(4)
)

# ============================================================
# CELL 25: PRECISION ROBUSTNESS HEATMAP
# ============================================================

fig, ax = plt.subplots(
    figsize=(9, 10)
)

image = ax.imshow(
    precision_matrix.values,
    aspect="auto"
)

ax.set_xticks(
    np.arange(len(precision_matrix.columns))
)

ax.set_xticklabels(
    precision_matrix.columns
)

ax.set_yticks(
    np.arange(len(precision_matrix.index))
)

ax.set_yticklabels(
    precision_matrix.index
)

ax.set_xlabel(
    "Training Augmentation Policy"
)

ax.set_ylabel(
    "Test Robustness Condition"
)

ax.set_title(
    "Precision Robustness Matrix"
)

for i in range(
    precision_matrix.shape[0]
):

    for j in range(
        precision_matrix.shape[1]
    ):

        ax.text(
            j,
            i,
            f"{precision_matrix.iloc[i, j]:.3f}",
            ha="center",
            va="center"
        )

fig.colorbar(
    image,
    ax=ax,
    label="Precision"
)

plt.tight_layout()
plt.show()

# ============================================================
# CELL 26: RECALL ROBUSTNESS HEATMAP
# ============================================================

fig, ax = plt.subplots(
    figsize=(9, 10)
)

image = ax.imshow(
    recall_matrix.values,
    aspect="auto"
)

ax.set_xticks(
    np.arange(len(recall_matrix.columns))
)

ax.set_xticklabels(
    recall_matrix.columns
)

ax.set_yticks(
    np.arange(len(recall_matrix.index))
)

ax.set_yticklabels(
    recall_matrix.index
)

ax.set_xlabel(
    "Training Augmentation Policy"
)

ax.set_ylabel(
    "Test Robustness Condition"
)

ax.set_title(
    "Recall Robustness Matrix"
)

for i in range(
    recall_matrix.shape[0]
):

    for j in range(
        recall_matrix.shape[1]
    ):

        ax.text(
            j,
            i,
            f"{recall_matrix.iloc[i, j]:.3f}",
            ha="center",
            va="center"
        )

fig.colorbar(
    image,
    ax=ax,
    label="Recall"
)

plt.tight_layout()
plt.show()

# ============================================================
# CELL 24: CLEAN TEST PERFORMANCE
# ============================================================

clean_results = (
    results_df[
        results_df["condition"] == "clean"
    ]
    [
        [
            "policy",
            "accuracy",
            "auc",
            "precision",
            "recall",
            "f1",
            "loss"
        ]
    ]
    .set_index("policy")
    .loc[POLICY_ORDER]
)

display(
    clean_results.round(4)
)

# ============================================================
# CELL 25: MEAN DISTORTION ROBUSTNESS
# ============================================================
# Clean is excluded because this statistic is intended to
# measure robustness specifically under distribution shift.

distorted_results = results_df[
    results_df["condition"] != "clean"
]

average_robustness = (
    distorted_results
    .groupby("policy")
    .agg(
        mean_accuracy=("accuracy", "mean"),
        mean_auc=("auc", "mean"),
        mean_precision=("precision", "mean"),
        mean_recall=("recall", "mean"),
        mean_f1=("f1", "mean")
    )
    .loc[POLICY_ORDER]
)

display(
    average_robustness.round(4)
)

# ============================================================
# CELL 26: ACCURACY DROP FROM CLEAN
# ============================================================
# A smaller performance drop indicates greater robustness
# relative to the model's own clean performance.

clean_accuracy = (
    results_df[
        results_df["condition"] == "clean"
    ]
    .set_index("policy")["accuracy"]
    .to_dict()
)

results_df[
    "accuracy_drop_from_clean"
] = results_df.apply(
    lambda row:
        clean_accuracy[row["policy"]]
        - row["accuracy"],
    axis=1
)

drop_matrix = results_df.pivot(
    index="condition",
    columns="policy",
    values="accuracy_drop_from_clean"
)

drop_matrix = drop_matrix[
    POLICY_ORDER
]

display(
    drop_matrix.round(4)
)

# ============================================================
# CELL 27: CONFUSION MATRIX FUNCTION
# ============================================================
# Positive class:
#     AI = 1
#
# Therefore:
#
# False Positive:
#     Real image incorrectly classified as AI.
#
# False Negative:
#     AI image incorrectly classified as Real.

def plot_confusion_matrix_for(
    predictions_df,
    policy,
    condition
):

    subset = predictions_df[
        (
            predictions_df["policy"] == policy
        )
        &
        (
            predictions_df["condition"] == condition
        )
    ]

    cm = confusion_matrix(
        subset["label"],
        subset["prediction"],
        labels=[0, 1]
    )

    fig, ax = plt.subplots(
        figsize=(5, 4)
    )

    image = ax.imshow(
        cm
    )

    ax.set_xticks(
        [0, 1]
    )

    ax.set_xticklabels(
        ["Real", "AI"]
    )

    ax.set_yticks(
        [0, 1]
    )

    ax.set_yticklabels(
        ["Real", "AI"]
    )

    ax.set_xlabel(
        "Predicted Class"
    )

    ax.set_ylabel(
        "True Class"
    )

    ax.set_title(
        f"{policy} — {condition}"
    )

    for i in range(2):

        for j in range(2):

            ax.text(
                j,
                i,
                cm[i, j],
                ha="center",
                va="center"
            )

    fig.colorbar(
        image,
        ax=ax
    )

    plt.tight_layout()
    plt.show()

    return cm

## Example

plot_confusion_matrix_for(
    predictions_df,
    policy="heldout",
    condition="clean"
)

# ============================================================
# CELL 28: WORST-CASE ROBUSTNESS CONDITION
# ============================================================

worst_conditions = (
    distorted_results
    .sort_values(
        "accuracy",
        ascending=True
    )
    .groupby(
        "policy",
        as_index=False
    )
    .first()
)

display(
    worst_conditions[
        [
            "policy",
            "condition",
            "accuracy",
            "auc",
            "precision",
            "recall",
            "f1"
        ]
    ].round(4)
)

# ============================================================
# CELL 29: MCNEMAR PAIRED TEST
# ============================================================
# McNemar's test compares two classifiers using predictions
# made on the exact same test images.
#
# H0:
# The two models have the same probability of making an error.
#
# A small p-value suggests that their difference in performance
# is unlikely to be explained only by random paired variation.

def mcnemar_test(
    predictions_df,
    policy_a,
    policy_b,
    condition
):

    a = predictions_df[
        (
            predictions_df["policy"] == policy_a
        )
        &
        (
            predictions_df["condition"] == condition
        )
    ][
        [
            "image_key",
            "label",
            "prediction"
        ]
    ].copy()

    b = predictions_df[
        (
            predictions_df["policy"] == policy_b
        )
        &
        (
            predictions_df["condition"] == condition
        )
    ][
        [
            "image_key",
            "prediction"
        ]
    ].copy()

    merged = a.merge(
        b,
        on="image_key",
        suffixes=("_a", "_b"),
        validate="one_to_one"
    )

    correct_a = (
        merged["prediction_a"]
        == merged["label"]
    )

    correct_b = (
        merged["prediction_b"]
        == merged["label"]
    )

    # A correct, B wrong.
    b_count = np.sum(
        correct_a
        &
        ~correct_b
    )

    # A wrong, B correct.
    c_count = np.sum(
        ~correct_a
        &
        correct_b
    )

    discordant = (
        b_count + c_count
    )

    if discordant == 0:

        p_value = 1.0

    else:

        p_value = binomtest(
            min(b_count, c_count),
            n=discordant,
            p=0.5,
            alternative="two-sided"
        ).pvalue

    return {
        "policy_a": policy_a,
        "policy_b": policy_b,
        "condition": condition,
        "a_correct_b_wrong": int(b_count),
        "a_wrong_b_correct": int(c_count),
        "p_value": p_value
    }

# ============================================================
# CELL 30: HELDOUT VS CONTINUOUS SIGNIFICANCE TESTS
# ============================================================

mcnemar_results = []

for condition in EVAL_SUITE:

    result = mcnemar_test(
        predictions_df,
        policy_a="heldout",
        policy_b="continuous",
        condition=condition
    )

    mcnemar_results.append(
        result
    )

mcnemar_df = pd.DataFrame(
    mcnemar_results
)

display(
    mcnemar_df
)

# ============================================================
# CELL 31: BOOTSTRAP CONFIDENCE INTERVAL FOR ACCURACY
# ============================================================

def bootstrap_accuracy_ci(
    labels,
    predictions,
    n_bootstrap=2000,
    confidence=0.95,
    seed=42
):

    rng = np.random.default_rng(
        seed
    )

    labels = np.asarray(
        labels
    )

    predictions = np.asarray(
        predictions
    )

    n = len(labels)

    bootstrap_scores = []

    for _ in range(
        n_bootstrap
    ):

        indices = rng.integers(
            0,
            n,
            size=n
        )

        score = np.mean(
            predictions[indices]
            ==
            labels[indices]
        )

        bootstrap_scores.append(
            score
        )

    alpha = (
        1 - confidence
    ) / 2

    lower = np.quantile(
        bootstrap_scores,
        alpha
    )

    upper = np.quantile(
        bootstrap_scores,
        1 - alpha
    )

    return lower, upper

# ============================================================
# CELL 32: ACCURACY CONFIDENCE INTERVALS
# ============================================================

ci_results = []

for policy in POLICY_ORDER:

    for condition in EVAL_SUITE:

        subset = predictions_df[
            (
                predictions_df["policy"] == policy
            )
            &
            (
                predictions_df["condition"] == condition
            )
        ]

        accuracy = np.mean(
            subset["prediction"]
            ==
            subset["label"]
        )

        lower, upper = bootstrap_accuracy_ci(
            subset["label"].to_numpy(),
            subset["prediction"].to_numpy()
        )

        ci_results.append({
            "policy": policy,
            "condition": condition,
            "accuracy": accuracy,
            "ci_lower": lower,
            "ci_upper": upper
        })

accuracy_ci_df = pd.DataFrame(
    ci_results
)

display(
    accuracy_ci_df.round(4)
)

# ============================================================
# CELL 33: SAVE ANALYSIS OUTPUTS
# ============================================================

accuracy_matrix.to_csv(
    os.path.join(
        RESULTS_DIR,
        "accuracy_matrix.csv"
    )
)

auc_matrix.to_csv(
    os.path.join(
        RESULTS_DIR,
        "auc_matrix.csv"
    )
)

drop_matrix.to_csv(
    os.path.join(
        RESULTS_DIR,
        "accuracy_drop_matrix.csv"
    )
)

average_robustness.to_csv(
    os.path.join(
        RESULTS_DIR,
        "average_robustness.csv"
    )
)

mcnemar_df.to_csv(
    os.path.join(
        RESULTS_DIR,
        "mcnemar_heldout_vs_continuous.csv"
    ),
    index=False
)

accuracy_ci_df.to_csv(
    os.path.join(
        RESULTS_DIR,
        "accuracy_confidence_intervals.csv"
    ),
    index=False
)

print(
    "All evaluation outputs saved."
)

# ============================================================
# CELL 34: SUMMARY OF MAIN RESULTS
# ============================================================

print("CLEAN TEST PERFORMANCE")
print("-" * 60)

display(
    clean_results[
        ["accuracy", "auc", "f1"]
    ].round(4)
)


print("\nMEAN DISTORTION ROBUSTNESS")
print("-" * 60)

display(
    average_robustness[
        [
            "mean_accuracy",
            "mean_auc",
            "mean_f1"
        ]
    ].round(4)
)


best_policy = (
    average_robustness[
        "mean_accuracy"
    ]
    .idxmax()
)

print(
    "\nHighest mean distorted accuracy:",
    best_policy
)


print(
    "\nWorst condition for each policy:"
)

display(
    worst_conditions[
        [
            "policy",
            "condition",
            "accuracy"
        ]
    ].round(4)
)

# ============================================================
# CELL 34b: RELOAD PREVIOUS RUN'S RESULTS (skip re-running CELLS 1-34)
# ============================================================

results_df = pd.read_csv(os.path.join(RESULTS_DIR, "aggregate_test_results.csv"))
predictions_df = pd.read_csv(os.path.join(RESULTS_DIR, "per_image_predictions.csv"))
average_robustness = pd.read_csv(os.path.join(RESULTS_DIR, "average_robustness.csv"), index_col="policy")
POLICY_ORDER = ["none", "continuous", "heldout", "spec"]

clean_results = (
    results_df[results_df["condition"] == "clean"]
    [["policy", "accuracy", "auc", "precision", "recall", "f1", "loss"]]
    .set_index("policy")
    .loc[POLICY_ORDER]
)

print("Reloaded:", len(results_df), "aggregate rows,", len(predictions_df), "per-image rows")
display(clean_results.round(4))

import os

base = "/content/drive/MyDrive"
for name in os.listdir(base):
    if "TikTok" in name:
        full = os.path.join(base, name)
        print(repr(name), "->", os.listdir(full) if os.path.isdir(full) else "not a dir")

VAL_ROOT = os.path.join("/content/dataset", "val")
print(os.path.exists(VAL_ROOT))
print(os.listdir(VAL_ROOT))

# ============================================================
# CELL 35: VALIDATION SET (reuses VAL_ROOT set during consolidation)
# ============================================================

print("VAL_ROOT:", VAL_ROOT)
print("Exists:", os.path.exists(VAL_ROOT))

VAL_SAMPLES = build_test_samples(VAL_ROOT)

print("Total val images:", len(VAL_SAMPLES))

val_dataset = RobustnessTestDataset(VAL_SAMPLES, eval_condition="clean")

val_loader = DataLoader(
    val_dataset, batch_size=BATCH_SIZE, shuffle=False,
    num_workers=NUM_WORKERS, pin_memory=True
)

# ============================================================
# CELL 36: RAW LOGIT EXTRACTION (needed for calibration)
# ============================================================

def get_val_logits(model, loader, device):
    model.eval()
    logits_all, labels_all = [], []

    with torch.no_grad():
        for images, labels, _ in loader:
            images = images.to(device, non_blocking=True)
            logits = model(images).squeeze(1)

            logits_all.extend(logits.cpu().numpy())
            labels_all.extend(labels.numpy())

    return np.asarray(logits_all), np.asarray(labels_all, dtype=int)

# ============================================================
# CELL 37: TEMPERATURE SCALING (fit T on val, frozen model)
# ============================================================

from scipy.optimize import minimize_scalar

def fit_temperature(logits, labels):
    logits = np.asarray(logits, dtype=np.float64)
    labels = np.asarray(labels, dtype=np.float64)

    def nll(T):
        T = max(T, 1e-3)
        probs = 1 / (1 + np.exp(-logits / T))
        probs = np.clip(probs, 1e-7, 1 - 1e-7)
        return -np.mean(labels * np.log(probs) + (1 - labels) * np.log(1 - probs))

    result = minimize_scalar(nll, bounds=(0.05, 10.0), method="bounded")
    return result.x

# ============================================================
# CELL 38: THRESHOLD SELECTION (Youden's J, on calibrated val probs)
# ============================================================

from sklearn.metrics import roc_curve

def select_threshold_youden(labels, calibrated_probs):
    fpr, tpr, thresholds = roc_curve(labels, calibrated_probs)
    j = tpr - fpr
    return float(thresholds[j.argmax()])

# ============================================================
# CELL 39: CALIBRATE + THRESHOLD EVERY CHECKPOINT ON VAL
# ============================================================

CALIBRATION = {}

for policy, checkpoint_path in CHECKPOINTS.items():
    model, _ = load_checkpoint_model(checkpoint_path, device)

    val_logits, val_labels = get_val_logits(model, val_loader, device)

    T = fit_temperature(val_logits, val_labels)
    calibrated_probs = 1 / (1 + np.exp(-val_logits / T))
    threshold = select_threshold_youden(val_labels, calibrated_probs)

    CALIBRATION[policy] = {"T": T, "threshold": threshold}
    print(f"{policy:12s}  T={T:.4f}  threshold={threshold:.4f}")

    del model
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

sample_dir = "/content/dataset/wildfake_clean/train/fake"
print(os.listdir(sample_dir)[:15])

# ============================================================
# CELL 40: WildFake-style REFERENCE BENCHMARK (COCO val2017 + DALL-E Advanced)
# ============================================================
# Two separate single-class zips, uploaded manually since the doc's
# curated subset isn't obtainable from the raw WildFake repo.
# Reference-only: not used in training, doesn't affect final score.

import zipfile

DEMO_LOCAL_DIR = "/content/demo_wildfake"
os.makedirs(DEMO_LOCAL_DIR, exist_ok=True)

DEMO_ZIPS = {
    "coco_val2017": {
        "drive_path": os.path.join(PROJECT_ROOT, "dataset", "cocoDemo.zip"),
        "label": 0,   # non-AIGC
    },
    "dalle_advanced": {
        "drive_path": os.path.join(PROJECT_ROOT, "dataset", "DallEDemo.zip"),
        "label": 1,   # AIGC
    },
}

for name, info in DEMO_ZIPS.items():
    extract_dir = os.path.join(DEMO_LOCAL_DIR, name)

    if os.path.exists(extract_dir):
        print(f"{name}: already extracted, skipping")
        continue

    local_zip = os.path.join("/content", f"{name}.zip")
    print(f"Copying {info['drive_path']} -> {local_zip}")
    shutil.copy(info["drive_path"], local_zip)

    print(f"Unzipping {name}...")
    with zipfile.ZipFile(local_zip, "r") as zip_ref:
        zip_ref.extractall(extract_dir)

    os.remove(local_zip)
    print(f"{name} extracted to {extract_dir}")

VALID_EXT = (".jpg", ".jpeg", ".png", ".webp", ".bmp")


def collect_images_recursive(root_dir, label):
    """
    Walks root_dir recursively and collects real image files, skipping:
    - __MACOSX/ folders (macOS zip metadata directory)
    - files starting with "._"  (macOS AppleDouble resource-fork files,
      created alongside every real file when zipping on a Mac -- these
      still end in .jpg/.png etc, so they silently double image counts
      if not filtered out here)
    """
    samples = []
    for current_dir, _, filenames in os.walk(root_dir):
        if "__MACOSX" in current_dir:
            continue
        for filename in sorted(filenames):
            if filename.startswith("._"):
                continue
            if filename.lower().endswith(VALID_EXT):
                filepath = os.path.join(current_dir, filename)
                samples.append({
                    "filepath": filepath,
                    "label": label,
                    "image_key": os.path.relpath(filepath, root_dir)
                })
    return samples


demo_samples = []
for name, info in DEMO_ZIPS.items():
    extract_dir = os.path.join(DEMO_LOCAL_DIR, name)
    found = collect_images_recursive(extract_dir, info["label"])
    print(f"{name}: {len(found)} images found")
    demo_samples.extend(found)

demo_samples = sorted(demo_samples, key=lambda x: x["image_key"])
print("Total demo images:", len(demo_samples))
print("Expected: 4998 (COCO) + 8843 (DALL-E) = 13841")

assert len(demo_samples) == 13841, (
    f"Got {len(demo_samples)} images, expected 13841 -- "
    "check for leftover macOS junk files or a genuine count mismatch "
    "before trusting downstream results."
)

demo_dataset = RobustnessTestDataset(demo_samples, eval_condition="clean")
demo_loader = DataLoader(demo_dataset, batch_size=BATCH_SIZE, shuffle=False,
                          num_workers=NUM_WORKERS, pin_memory=True)

heldout_model, _ = load_checkpoint_model(CHECKPOINTS["heldout"], device)
T = CALIBRATION["heldout"]["T"]
threshold = CALIBRATION["heldout"]["threshold"]

demo_logits, demo_labels = get_val_logits(heldout_model, demo_loader, device)
demo_probs = 1 / (1 + np.exp(-demo_logits / T))
demo_preds = (demo_probs >= threshold).astype(int)

demo_results = pd.DataFrame({
    "image_key": [s["image_key"] for s in demo_samples],
    "label": demo_labels,
    "probability_ai": demo_probs,
    "prediction": demo_preds,
})

acc = np.mean(demo_preds == demo_labels)
auc = roc_auc_score(demo_labels, demo_probs)
print(f"WildFake reference benchmark -- heldout: accuracy={acc:.4f}, AUC={auc:.4f}")

demo_results.to_csv(os.path.join(RESULTS_DIR, "wildfake_reference_results.csv"), index=False)

# ============================================================
# CELL 41: COMPACT ROBUSTNESS SUMMARY TABLE
# ============================================================

robustness_summary = pd.DataFrame({
    "clean_accuracy": clean_results["accuracy"],
    "mean_distorted_accuracy": average_robustness["mean_accuracy"],
    "accuracy_drop": clean_results["accuracy"] - average_robustness["mean_accuracy"],
    "clean_auc": clean_results["auc"],
    "mean_distorted_auc": average_robustness["mean_auc"],
}).loc[POLICY_ORDER]

display(robustness_summary.round(4))
robustness_summary.to_csv(os.path.join(RESULTS_DIR, "robustness_summary.csv"))

# ============================================================
# CELL 42: REPRESENTATIVE FALSE POSITIVES / NEGATIVES
# ============================================================

def get_representative_errors(predictions_df, policy, condition="clean", n=5):
    subset = predictions_df[
        (predictions_df["policy"] == policy) & (predictions_df["condition"] == condition)
    ]

    false_positives = subset[(subset["label"] == 0) & (subset["prediction"] == 1)]
    false_negatives = subset[(subset["label"] == 1) & (subset["prediction"] == 0)]

    # Sorting by probability surfaces the *most confidently wrong* cases --
    # these are the most informative failure modes to discuss, not just any error.
    top_fp = false_positives.sort_values("probability", ascending=False).head(n)
    top_fn = false_negatives.sort_values("probability", ascending=True).head(n)

    return top_fp, top_fn


def show_error_examples(df, title, root_dir):
    if len(df) == 0:
        print(f"{title}: none found")
        return
    fig, axes = plt.subplots(1, len(df), figsize=(3 * len(df), 3))
    axes = [axes] if len(df) == 1 else axes
    for ax, (_, row) in zip(axes, df.iterrows()):
        img = Image.open(os.path.join(root_dir, row["image_key"])).convert("RGB")
        ax.imshow(img)
        ax.set_title(f'{row["probability"]:.3f}')
        ax.axis("off")
    fig.suptitle(title)
    plt.tight_layout()
    plt.show()


top_fp, top_fn = get_representative_errors(predictions_df, policy="heldout")

show_error_examples(top_fp, "False Positives (Real → predicted AI)", TEST_ROOT)
show_error_examples(top_fn, "False Negatives (AI → predicted Real)", TEST_ROOT)

top_fp[["image_key", "probability"]].to_csv(
    os.path.join(RESULTS_DIR, "error_analysis_false_positives.csv"), index=False)
top_fn[["image_key", "probability"]].to_csv(
    os.path.join(RESULTS_DIR, "error_analysis_false_negatives.csv"), index=False)

# What was heldout's AUC on the original locked test set?
print(clean_results.loc["heldout"])
print(pd.Series(demo_preds).value_counts())
print(demo_results.groupby("label")["probability_ai"].describe())

import random
sample_check = random.sample(demo_samples, 4)
fig, axes = plt.subplots(1, 4, figsize=(12, 3))
for ax, s in zip(axes, sample_check):
    img = Image.open(s["filepath"]).convert("RGB")
    ax.imshow(img)
    ax.set_title(f'label={s["label"]}, {img.size}')
    ax.axis("off")
plt.show()

for policy in ["none", "spec", "continuous"]:
    m, _ = load_checkpoint_model(CHECKPOINTS[policy], device)
    logits, labels = get_val_logits(m, demo_loader, device)
    probs = 1 / (1 + np.exp(-logits))  # uncalibrated AUC is fine, ranking-only
    print(policy, "AUC:", roc_auc_score(labels, probs))
    del m