# -*- coding: utf-8 -*-
"""model_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N2fqG5R4qXVN563s1QiqD4SGeiingjsd

# Model Training

## Imports and Configs
"""

!git clone https://github.com/TechJammers-26/AI-Image-Detection.git

from google.colab import drive
drive.mount('/content/gdrive')

GOOGLE_DRIVE_DATASET_PATH = '/content/gdrive/MyDrive/1_TikTok_TechJam_2026'

# Define the local directory where the dataset will be stored and unzipped
DATASET_DIR = '/content/dataset'
os.makedirs(DATASET_DIR, exist_ok=True)

# List of zip file names to process from GOOGLE_DRIVE_DATASET_PATH
ZIP_FILE_NAMES = [
    'sid_clean.zip',
    'cifake_clean.zip',
    'wildfake_clean.zip'
]

# Define TRAIN_ROOT and VAL_ROOT based on the local dataset directory
TRAIN_ROOT = os.path.join(DATASET_DIR, "train")
VAL_ROOT = os.path.join(DATASET_DIR, "val")

print(f"TRAIN_ROOT set to: {TRAIN_ROOT}")
print(f"VAL_ROOT set to: {VAL_ROOT}")

import zipfile

print(f"Starting dataset extraction to: {DATASET_DIR}")

for zip_file_name in ZIP_FILE_NAMES:
    # Construct the full path to the zip file in Google Drive
    google_drive_zip_path = os.path.join(GOOGLE_DRIVE_DATASET_PATH, zip_file_name)

    # Define a temporary path for the zip file in the Colab environment
    temp_zip_path = os.path.join('/content', zip_file_name)

    print(f"Copying {zip_file_name} from Google Drive...")
    # Copy the zip file from Google Drive to the Colab environment
    !cp "{google_drive_zip_path}" "{temp_zip_path}"
    print(f"Copied {zip_file_name} to {temp_zip_path}")

    print(f"Unzipping {zip_file_name}...")
    # Unzip the file into the DATASET_DIR
    with zipfile.ZipFile(temp_zip_path, 'r') as zip_ref:
        zip_ref.extractall(DATASET_DIR)
    print(f"Unzipped {zip_file_name} to {DATASET_DIR}")

    # Remove the temporary zip file to save space
    os.remove(temp_zip_path)
    print(f"Removed temporary zip file: {temp_zip_path}")

print("All datasets extracted successfully!")

import shutil

# Define the target consolidated directories
CONSOLIDATED_TRAIN_ROOT = os.path.join(DATASET_DIR, "train")
CONSOLIDATED_VAL_ROOT = os.path.join(DATASET_DIR, "val")

# Create the consolidated root directories
os.makedirs(os.path.join(CONSOLIDATED_TRAIN_ROOT, "real"), exist_ok=True)
os.makedirs(os.path.join(CONSOLIDATED_TRAIN_ROOT, "ai"), exist_ok=True)
os.makedirs(os.path.join(CONSOLIDATED_VAL_ROOT, "real"), exist_ok=True)
os.makedirs(os.path.join(CONSOLIDATED_VAL_ROOT, "ai"), exist_ok=True)

# List of unzipped dataset base directories
UNZIPPED_DATASET_DIRS = [
    os.path.join(DATASET_DIR, 'sid_clean'),
    os.path.join(DATASET_DIR, 'cifake_dataset_clean'),
    os.path.join(DATASET_DIR, 'wildfake_clean')
]

print("Consolidating datasets...")

for dataset_base_dir in UNZIPPED_DATASET_DIRS:
    print(f"Processing dataset: {dataset_base_dir}")

    for split in ['train', 'val']:
        source_split_dir = os.path.join(dataset_base_dir, split)

        # Process 'real' class
        source_real_dir = os.path.join(source_split_dir, 'real')
        target_real_dir = os.path.join(CONSOLIDATED_TRAIN_ROOT if split == 'train' else CONSOLIDATED_VAL_ROOT, 'real')
        if os.path.exists(source_real_dir):
            for filename in os.listdir(source_real_dir):
                shutil.move(os.path.join(source_real_dir, filename), target_real_dir)
            print(f"Moved real images from {source_real_dir} to {target_real_dir}")

        # Process 'fake' (to be renamed 'ai') class
        source_fake_dir = os.path.join(source_split_dir, 'fake')
        target_ai_dir = os.path.join(CONSOLIDATED_TRAIN_ROOT if split == 'train' else CONSOLIDATED_VAL_ROOT, 'ai')
        if os.path.exists(source_fake_dir):
            for filename in os.listdir(source_fake_dir):
                shutil.move(os.path.join(source_fake_dir, filename), target_ai_dir)
            print(f"Moved fake images from {source_fake_dir} to {target_ai_dir} (as ai)")

# Clean up original unzipped dataset directories (optional, but good for space)
print("Cleaning up original dataset folders...")
for dataset_base_dir in UNZIPPED_DATASET_DIRS:
    if os.path.exists(dataset_base_dir):
        shutil.rmtree(dataset_base_dir)
        print(f"Removed {dataset_base_dir}")

print("Dataset consolidation complete!")

# Re-run the TRAIN_ROOT and VAL_ROOT definition after consolidation
TRAIN_ROOT = CONSOLIDATED_TRAIN_ROOT
VAL_ROOT = CONSOLIDATED_VAL_ROOT

print(f"TRAIN_ROOT re-set to: {TRAIN_ROOT}")
print(f"VAL_ROOT re-set to: {VAL_ROOT}")

# # Re-run the directory listing to verify the new structure
# print(f"Contents of {DATASET_DIR} after consolidation:")
# !ls -R {DATASET_DIR}

import shutil

# Define the target consolidated directories
CONSOLIDATED_TRAIN_ROOT = os.path.join(DATASET_DIR, "train")
CONSOLIDATED_VAL_ROOT = os.path.join(DATASET_DIR, "val")

# Create the consolidated root directories
os.makedirs(os.path.join(CONSOLIDATED_TRAIN_ROOT, "real"), exist_ok=True)
os.makedirs(os.path.join(CONSOLIDATED_TRAIN_ROOT, "ai"), exist_ok=True)
os.makedirs(os.path.join(CONSOLIDATED_VAL_ROOT, "real"), exist_ok=True)
os.makedirs(os.path.join(CONSOLIDATED_VAL_ROOT, "ai"), exist_ok=True)

# List of unzipped dataset base directories
UNZIPPED_DATASET_DIRS = [
    os.path.join(DATASET_DIR, 'sid_clean'),
    os.path.join(DATASET_DIR, 'cifake_dataset_clean'),
    os.path.join(DATASET_DIR, 'wildfake_clean')
]

print("Consolidating datasets...")

for dataset_base_dir in UNZIPPED_DATASET_DIRS:
    print(f"Processing dataset: {dataset_base_dir}")

    for split in ['train', 'val']:
        source_split_dir = os.path.join(dataset_base_dir, split)

        # Process 'real' class
        source_real_dir = os.path.join(source_split_dir, 'real')
        target_real_dir = os.path.join(CONSOLIDATED_TRAIN_ROOT if split == 'train' else CONSOLIDATED_VAL_ROOT, 'real')
        if os.path.exists(source_real_dir):
            for filename in os.listdir(source_real_dir):
                shutil.move(os.path.join(source_real_dir, filename), target_real_dir)
            print(f"Moved real images from {source_real_dir} to {target_real_dir}")

        # Process 'fake' (to be renamed 'ai') class
        source_fake_dir = os.path.join(source_split_dir, 'fake')
        target_ai_dir = os.path.join(CONSOLIDATED_TRAIN_ROOT if split == 'train' else CONSOLIDATED_VAL_ROOT, 'ai')
        if os.path.exists(source_fake_dir):
            for filename in os.listdir(source_fake_dir):
                shutil.move(os.path.join(source_fake_dir, filename), target_ai_dir)
            print(f"Moved fake images from {source_fake_dir} to {target_ai_dir} (as ai)")

# Clean up original unzipped dataset directories (optional, but good for space)
print("Cleaning up original dataset folders...")
for dataset_base_dir in UNZIPPED_DATASET_DIRS:
    if os.path.exists(dataset_base_dir):
        shutil.rmtree(dataset_base_dir)
        print(f"Removed {dataset_base_dir}")

print("Dataset consolidation complete!")

# Re-run the TRAIN_ROOT and VAL_ROOT definition after consolidation
TRAIN_ROOT = CONSOLIDATED_TRAIN_ROOT
VAL_ROOT = CONSOLIDATED_VAL_ROOT

print(f"TRAIN_ROOT re-set to: {TRAIN_ROOT}")
print(f"VAL_ROOT re-set to: {VAL_ROOT}")

# # Re-run the directory listing to verify the new structure
# print(f"Contents of {DATASET_DIR} after consolidation:")
# !ls -R {DATASET_DIR}

import shutil

# Define the target consolidated directories
CONSOLIDATED_TRAIN_ROOT = os.path.join(DATASET_DIR, "train")
CONSOLIDATED_VAL_ROOT = os.path.join(DATASET_DIR, "val")

# Create the consolidated root directories
os.makedirs(os.path.join(CONSOLIDATED_TRAIN_ROOT, "real"), exist_ok=True)
os.makedirs(os.path.join(CONSOLIDATED_TRAIN_ROOT, "ai"), exist_ok=True)
os.makedirs(os.path.join(CONSOLIDATED_VAL_ROOT, "real"), exist_ok=True)
os.makedirs(os.path.join(CONSOLIDATED_VAL_ROOT, "ai"), exist_ok=True)

# List of unzipped dataset base directories
UNZIPPED_DATASET_DIRS = [
    os.path.join(DATASET_DIR, 'sid_clean'),
    os.path.join(DATASET_DIR, 'cifake_dataset_clean'),
    os.path.join(DATASET_DIR, 'wildfake_clean')
]

print("Consolidating datasets...")

for dataset_base_dir in UNZIPPED_DATASET_DIRS:
    print(f"Processing dataset: {dataset_base_dir}")

    for split in ['train', 'val']:
        source_split_dir = os.path.join(dataset_base_dir, split)

        # Process 'real' class
        source_real_dir = os.path.join(source_split_dir, 'real')
        target_real_dir = os.path.join(CONSOLIDATED_TRAIN_ROOT if split == 'train' else CONSOLIDATED_VAL_ROOT, 'real')
        if os.path.exists(source_real_dir):
            for filename in os.listdir(source_real_dir):
                shutil.move(os.path.join(source_real_dir, filename), target_real_dir)
            print(f"Moved real images from {source_real_dir} to {target_real_dir}")

        # Process 'fake' (to be renamed 'ai') class
        source_fake_dir = os.path.join(source_split_dir, 'fake')
        target_ai_dir = os.path.join(CONSOLIDATED_TRAIN_ROOT if split == 'train' else CONSOLIDATED_VAL_ROOT, 'ai')
        if os.path.exists(source_fake_dir):
            for filename in os.listdir(source_fake_dir):
                shutil.move(os.path.join(source_fake_dir, filename), target_ai_dir)
            print(f"Moved fake images from {source_fake_dir} to {target_ai_dir} (as ai)")

# Clean up original unzipped dataset directories (optional, but good for space)
print("Cleaning up original dataset folders...")
for dataset_base_dir in UNZIPPED_DATASET_DIRS:
    if os.path.exists(dataset_base_dir):
        shutil.rmtree(dataset_base_dir)
        print(f"Removed {dataset_base_dir}")

print("Dataset consolidation complete!")

# Define TRAIN_ROOT and VAL_ROOT based on the local dataset directory
TRAIN_ROOT = os.path.join(DATASET_DIR, "train")
VAL_ROOT = os.path.join(DATASET_DIR, "val")

print(f"TRAIN_ROOT set to: {TRAIN_ROOT}")
print(f"VAL_ROOT set to: {VAL_ROOT}")

# List the contents of the dataset directory to verify
print(f"Contents of {DATASET_DIR}:")
!ls -R {DATASET_DIR}

import os
import sys
import copy
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from PIL import Image

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import models, transforms

from sklearn.metrics import accuracy_score, roc_auc_score

# Checking device

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Device:", device)

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

# Reproducibility

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

# Model Configurations

BACKBONE = "efficientnet_b0"

# Choose ONE:
# "none"
# "continuous"
# "heldout"
# "spec"

POLICY = "none"

IMAGE_SIZE = 224
BATCH_SIZE = 32

EPOCHS = 6

LEARNING_RATE = 1e-4
WEIGHT_DECAY = 1e-4

NUM_WORKERS = 2


# Checkpoint Path

CHECKPOINT_DIR = "/content/checkpoints"

os.makedirs(CHECKPOINT_DIR, exist_ok=True)

CHECKPOINT_PATH = os.path.join(
    CHECKPOINT_DIR,
    f"{BACKBONE}_{POLICY}_best.pth"
)

print("Policy:", POLICY)
print("Checkpoint will be saved to:")
print(CHECKPOINT_PATH)

"""## Loading and Creating Training Augmentation Policies"""

# Connect to Repo for Augmentation functions

REPO_PATH = "/content/AI-Image-Detection/src/aigcdet"

if REPO_PATH not in sys.path:
    sys.path.append(REPO_PATH)

from augmentations import (
    build_train_augment,
    apply_eval_transform,
    eval_names,
    get_eval_transform,
    canonicalize
)

print("augmentations.py imported successfully!")

train_augmenter = build_train_augment(
    policy=POLICY,
    n_ops=(0, 2),
    p=0.9,
    seed=SEED
)

augmentation_config = train_augmenter.config()

augmentation_config

"""## Data Preparation for Modelling

```
dataset/
│
├── train/
│   ├── real/
│   └── ai/
│
└── val/
    ├── real/
    └── ai/
```
"""

class AIImageDataset(Dataset):
    def __init__(self, root_dir, transform=None):
        self.root_dir = root_dir
        self.transform = transform

        self.samples = []

        # Explicit label convention
        class_mapping = {
            "real": 0,
            "ai": 1
        }

        valid_extensions = (
            ".jpg",
            ".jpeg",
            ".png",
            ".webp",
            ".bmp"
        )

        for class_name, label in class_mapping.items():

            class_dir = os.path.join(
                root_dir,
                class_name
            )

            if not os.path.exists(class_dir):
                raise FileNotFoundError(
                    f"Cannot find folder: {class_dir}"
                )

            for filename in os.listdir(class_dir):

                if filename.lower().endswith(valid_extensions):

                    filepath = os.path.join(
                        class_dir,
                        filename
                    )

                    self.samples.append(
                        (filepath, label)
                    )

        print(
            f"Loaded {len(self.samples)} images "
            f"from {root_dir}"
        )

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):

        filepath, label = self.samples[idx]

        image = Image.open(filepath).convert("RGB")

        if self.transform is not None:
            image = self.transform(image)

        return image, label

"""## Data Loading"""

train_transform = transforms.Compose([
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

val_transform = transforms.Compose([
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

try:
    train_dataset = AIImageDataset(
        root_dir=TRAIN_ROOT,
        transform=train_transform
    )

    val_dataset = AIImageDataset(
        root_dir=VAL_ROOT,
        transform=val_transform
    )
except FileNotFoundError as e:
    print(f"Error: {e}. Please ensure the dataset directories are correctly set up.")
    # You might want to halt execution or provide further instructions here
    train_dataset = None
    val_dataset = None

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True
)

print("Training batches:", len(train_loader))
print("Validation batches:", len(val_loader))

images, labels = next(iter(train_loader))

print("Image batch shape:", images.shape)
print("Label batch shape:", labels.shape)
print("Example labels:", labels[:10])

"""## Baseline Model

```
Input Image
    ↓
Preprocessing / Training Augmentation
    ↓
Pretrained Backbone
(ResNet-50 OR EfficientNet-B0)
    ↓
Binary Classification Head
    ↓
Logit
    ↓
Sigmoid
    ↓
P(AI-generated)
```


```
Real = 0
AI   = 1
```
"""

weights = models.EfficientNet_B0_Weights.DEFAULT

model = models.efficientnet_b0(
    weights=weights
)

print(model.classifier)

in_features = model.classifier[1].in_features

model.classifier[1] = nn.Linear(
    in_features,
    1
)

model = model.to(device)

print(model.classifier)

# Loss + Optimisation

criterion = nn.BCEWithLogitsLoss()

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY
)

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer,
    T_max=EPOCHS
)

def train_one_epoch(
    model,
    loader,
    criterion,
    optimizer,
    device
):

    model.train()

    total_loss = 0

    probabilities = []
    ground_truth = []

    for images, labels in loader:

        images = images.to(
            device,
            non_blocking=True
        )

        # IMPORTANT: BCEWithLogitsLoss needs FLOAT labels
        labels = labels.float().to(
            device,
            non_blocking=True
        )

        optimizer.zero_grad()

        # Forward
        logits = model(images).squeeze(1)

        # Loss
        loss = criterion(
            logits,
            labels
        )

        # Backprop
        loss.backward()

        optimizer.step()

        total_loss += (
            loss.item()
            * images.size(0)
        )

        probs = torch.sigmoid(logits)

        probabilities.extend(
            probs.detach().cpu().numpy()
        )

        ground_truth.extend(
            labels.detach().cpu().numpy()
        )

    epoch_loss = (
        total_loss / len(loader.dataset)
    )

    probabilities = np.array(probabilities)
    ground_truth = np.array(ground_truth)

    predictions = (
        probabilities >= 0.5
    ).astype(int)

    accuracy = accuracy_score(
        ground_truth,
        predictions
    )

    auc = roc_auc_score(
        ground_truth,
        probabilities
    )

    return (
        epoch_loss,
        accuracy,
        auc
    )

# ============================================================
# CELL 11 — VALIDATE CLEAN
# ============================================================

def evaluate_model(
    model,
    loader,
    criterion,
    device
):

    model.eval()

    total_loss = 0

    probabilities = []
    ground_truth = []

    with torch.no_grad():

        for images, labels in loader:

            images = images.to(
                device,
                non_blocking=True
            )

            labels = labels.float().to(
                device,
                non_blocking=True
            )

            logits = model(
                images
            ).squeeze(1)

            loss = criterion(
                logits,
                labels
            )

            total_loss += (
                loss.item()
                * images.size(0)
            )

            probs = torch.sigmoid(
                logits
            )

            probabilities.extend(
                probs.cpu().numpy()
            )

            ground_truth.extend(
                labels.cpu().numpy()
            )

    loss = (
        total_loss
        /
        len(loader.dataset)
    )

    probabilities = np.array(
        probabilities
    )

    ground_truth = np.array(
        ground_truth
    )

    predictions = (
        probabilities >= 0.5
    ).astype(int)

    accuracy = accuracy_score(
        ground_truth,
        predictions
    )

    auc = roc_auc_score(
        ground_truth,
        probabilities
    )

    return (
        loss,
        accuracy,
        auc
    )

# ============================================================
# CELL 12 — TRAINING LOOP
# ============================================================

history = {
    "epoch": [],
    "train_loss": [],
    "train_accuracy": [],
    "train_auc": [],
    "val_loss": [],
    "val_accuracy": [],
    "val_auc": []
}

best_val_accuracy = -1.0
best_epoch = -1

for epoch in range(EPOCHS):

    print()
    print(
        f"Epoch "
        f"{epoch + 1}/{EPOCHS}"
    )

    print("=" * 50)

    # TRAIN
    (
        train_loss,
        train_accuracy,
        train_auc
    ) = train_one_epoch(
        model,
        train_loader,
        criterion,
        optimizer,
        device
    )

    # CLEAN VALIDATION
    (
        val_loss,
        val_accuracy,
        val_auc
    ) = evaluate_model(
        model,
        val_loader,
        criterion,
        device
    )

    # SAVE HISTORY
    history["epoch"].append(
        epoch + 1
    )

    history["train_loss"].append(
        train_loss
    )

    history["train_accuracy"].append(
        train_accuracy
    )

    history["train_auc"].append(
        train_auc
    )

    history["val_loss"].append(
        val_loss
    )

    history["val_accuracy"].append(
        val_accuracy
    )

    history["val_auc"].append(
        val_auc
    )

    print(
        f"Train Loss: "
        f"{train_loss:.4f}"
    )

    print(
        f"Train Accuracy: "
        f"{train_accuracy:.4f}"
    )

    print(
        f"Train AUC: "
        f"{train_auc:.4f}"
    )

    print()

    print(
        f"Clean Val Loss: "
        f"{val_loss:.4f}"
    )

    print(
        f"Clean Val Accuracy: "
        f"{val_accuracy:.4f}"
    )

    print(
        f"Clean Val AUC: "
        f"{val_auc:.4f}"
    )

    # SAVE BEST CHECKPOINT

    if (
        val_accuracy
        >
        best_val_accuracy
    ):

        best_val_accuracy = (
            val_accuracy
        )

        best_epoch = (
            epoch + 1
        )

        checkpoint = {

            "epoch":
                best_epoch,

            "model_state_dict":
                model.state_dict(),

            "optimizer_state_dict":
                optimizer.state_dict(),

            "val_accuracy":
                val_accuracy,

            "val_auc":
                val_auc,

            "val_loss":
                val_loss,

            "policy":
                POLICY,

            "augmentation_config":
                train_augmenter.config(),

            "backbone":
                BACKBONE,

            "image_size":
                IMAGE_SIZE,

            "batch_size":
                BATCH_SIZE,

            "learning_rate":
                LEARNING_RATE
        }

        torch.save(
            checkpoint,
            CHECKPOINT_PATH
        )

        print()
        print(
            "✓ New best checkpoint saved"
        )

        print(
            "Best epoch:",
            best_epoch
        )

        print(
            "Best accuracy:",
            f"{best_val_accuracy:.4f}"
        )

    scheduler.step()

print()
print("=" * 50)

print("TRAINING COMPLETE")

print(
    "Policy:",
    POLICY
)

print(
    "Best epoch:",
    best_epoch
)

print(
    "Best clean accuracy:",
    best_val_accuracy
)

print(
    "Checkpoint:",
    CHECKPOINT_PATH
)

### PLOT TRAINING HISTORY ###


history_df = pd.DataFrame(history)

history_df


## Validation Loss

plt.figure(figsize=(8, 5))

plt.plot(
    history_df["epoch"],
    history_df["train_loss"],
    label="Train Loss"
)

plt.plot(
    history_df["epoch"],
    history_df["val_loss"],
    label="Validation Loss"
)

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title(
    f"Loss — EfficientNet-B0 ({POLICY})"
)

plt.legend()
plt.show()


## Training Accuracy

plt.figure(figsize=(8, 5))

plt.plot(
    history_df["epoch"],
    history_df["train_accuracy"],
    label="Train Accuracy"
)

plt.plot(
    history_df["epoch"],
    history_df["val_accuracy"],
    label="Clean Validation Accuracy"
)

plt.xlabel("Epoch")
plt.ylabel("Accuracy")

plt.title(
    f"Accuracy — EfficientNet-B0 ({POLICY})"
)

plt.legend()
plt.show()


## AUC
plt.figure(figsize=(8, 5))

plt.plot(
    history_df["epoch"],
    history_df["train_auc"],
    label="Train AUC"
)

plt.plot(
    history_df["epoch"],
    history_df["val_auc"],
    label="Clean Validation AUC"
)

plt.xlabel("Epoch")
plt.ylabel("ROC-AUC")

plt.title(
    f"AUC — EfficientNet-B0 ({POLICY})"
)

plt.legend()
plt.show()

checkpoint = torch.load(
    CHECKPOINT_PATH,
    map_location=device,
    weights_only=False
)

model.load_state_dict(
    checkpoint["model_state_dict"]
)

model = model.to(device)

print("Loaded checkpoint:")
print("Policy:", checkpoint["policy"])
print("Best epoch:", checkpoint["epoch"])
print("Clean val accuracy:", checkpoint["val_accuracy"])
print("Clean val AUC:", checkpoint["val_auc"])


