# -*- coding: utf-8 -*-
"""augmentation_transforms.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19rLBCunmnyeALzqlLLE8nI-UUAr2xjzt

Connect to GPU
"""

import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU")

"""Setup **(Run once every session)**"""

# Commented out IPython magic to ensure Python compatibility.
#!git clone https://github.com/TechJammers-26/AI-Image-Detection.git
# %cd /content/AI-Image-Detection
#!pip install -r requirements.txt --break-system-packages -q

import sys
sys.path.append('/content/AI-Image-Detection/src')

from aigcdet import augmentations

"""Run smoke test"""

#!python scripts/smoke_test.py

"""List available transform conditions"""

#!python scripts/make_transformed_sets.py --list

"""Visually inspect transforms"""

#!python scripts/transform_gallery.py --out outputs/gallery.png
from IPython.display import Image as IPImage
IPImage("outputs/gallery.png")

"""Run the augmentation test suite"""

#!python tests/test_augmentations.py

"""(If you're actively editing code) Pull latest + reload"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/AI-Image-Detection
#!git pull
# %cd /content
import importlib
importlib.reload(augmentations)

